class AddAllOrganizations2 extends edu.northwestern.bioinformatics.bering.Migration {

  void up() {
		m0()
		m1()
		m2()
		m3()
		m4()
		m5()
		m6()
		m7()
		m8()
		m9()
   }
  
	void m0(){
		insert('organizations', [id: 109012 , nci_institute_code:  "SC095" , name: "Gibbs Cancer Center-Gaffney"], primaryKey: false)
		insert('organizations', [id: 109013 , nci_institute_code:  "SC096" , name: "Carolina Cancer Specialists"], primaryKey: false)
		insert('organizations', [id: 109014 , nci_institute_code:  "SC098" , name: "Coastal Oncology"], primaryKey: false)
		insert('organizations', [id: 109015 , nci_institute_code:  "SC099" , name: "BI-LO Charities Children's Cancer Center"], primaryKey: false)
		insert('organizations', [id: 109016 , nci_institute_code:  "SC100" , name: "Carolina Urologic Research Center"], primaryKey: false)
		insert('organizations', [id: 109017 , nci_institute_code:  "SC101" , name: "Gibbs Cancer Center-Pelham"], primaryKey: false)
		insert('organizations', [id: 109018 , nci_institute_code:  "SC102" , name: "Lancaster Radiation Therapy Center"], primaryKey: false)
		insert('organizations', [id: 109019 , nci_institute_code:  "SD039" , name: "Sanford Children's Specialty Clinic-Sioux Falls"], primaryKey: false)
		insert('organizations', [id: 109020 , nci_institute_code:  "SD040" , name: "Comprehensive Breast Care"], primaryKey: false)
		insert('organizations', [id: 109021 , nci_institute_code:  "SD041" , name: "Avera Medical Group McHale Institute"], primaryKey: false)
		insert('organizations', [id: 109022 , nci_institute_code:  "TN169" , name: "Innovative Pathology Services"], primaryKey: false)
		insert('organizations', [id: 109023 , nci_institute_code:  "TN170" , name: "Associates in Diagnostic Radiology PC and Plaza Radiology LLC"], primaryKey: false)
		insert('organizations', [id: 109024 , nci_institute_code:  "TN172" , name: "The Jackson Clinic PA"], primaryKey: false)
		insert('organizations', [id: 109025 , nci_institute_code:  "TN173" , name: "Family Cancer Center-Memphis"], primaryKey: false)
		insert('organizations', [id: 109026 , nci_institute_code:  "TN174" , name: "The Center for Biomedical Research"], primaryKey: false)
		insert('organizations', [id: 109027 , nci_institute_code:  "TN175" , name: "Tennessee Cancer Specialists-Dowell Springs"], primaryKey: false)
		insert('organizations', [id: 109028 , nci_institute_code:  "TN177" , name: "Mountain States Health Alliance"], primaryKey: false)
		insert('organizations', [id: 109029 , nci_institute_code:  "TN178" , name: "Regional Cancer Center at Johnson City Medical Center"], primaryKey: false)
		insert('organizations', [id: 109030 , nci_institute_code:  "TN179" , name: "Discovery Alliance-Compass Point Research"], primaryKey: false)
		insert('organizations', [id: 109031 , nci_institute_code:  "TN180" , name: "Chattanooga Surgical Oncology and Associates"], primaryKey: false)
		insert('organizations', [id: 109032 , nci_institute_code:  "TN181" , name: "Vanderbilt Breast Center at One Hundred Oaks"], primaryKey: false)
		insert('organizations', [id: 109033 , nci_institute_code:  "TN182" , name: "Thompson Cancer Survival Center West"], primaryKey: false)
		insert('organizations', [id: 109034 , nci_institute_code:  "TN183" , name: "Integrity Oncology PLLC-Memphis"], primaryKey: false)
		insert('organizations', [id: 109035 , nci_institute_code:  "TN185" , name: "Family Cancer Center PLLC"], primaryKey: false)
		insert('organizations', [id: 109036 , nci_institute_code:  "TN186" , name: "East Tennessee Pediatric Surgery Group PLLC"], primaryKey: false)
	}
	
	void m1(){
		insert('organizations', [id: 109037 , nci_institute_code:  "TN187" , name: "Wellmont CVA Heart Institute-Kingsport"], primaryKey: false)
		insert('organizations', [id: 109038 , nci_institute_code:  "TN188" , name: "Vanderbilt-Ingram Cancer Center at Green Hills"], primaryKey: false)
		insert('organizations', [id: 109039 , nci_institute_code:  "TN189" , name: "Thompson Oncology Group-Oak Ridge"], primaryKey: false)
		insert('organizations', [id: 109040 , nci_institute_code:  "TN190" , name: "Thompson Oncology Group-Maryville"], primaryKey: false)
		insert('organizations', [id: 109041 , nci_institute_code:  "TN191" , name: "Indian Path Medical/Cancer Center-MSHA"], primaryKey: false)
		insert('organizations', [id: 109042 , nci_institute_code:  "TN192" , name: "The Jackson Clinic-North Pediatric"], primaryKey: false)
		insert('organizations', [id: 109043 , nci_institute_code:  "TN193" , name: "Tennessee Oncology PLLC-Shelbyville"], primaryKey: false)
		insert('organizations', [id: 109044 , nci_institute_code:  "TN194" , name: "The West Clinic Comprehensive Breast Center"], primaryKey: false)
		insert('organizations', [id: 109045 , nci_institute_code:  "TN195" , name: "Wellmont Medical Associates Women's Cancer Services"], primaryKey: false)
		insert('organizations', [id: 109046 , nci_institute_code:  "TX337" , name: "Surgical Oncology Associates of South Texas"], primaryKey: false)
		insert('organizations', [id: 109047 , nci_institute_code:  "TX338" , name: "Richardson Regional Medical Center-Bush"], primaryKey: false)
		insert('organizations', [id: 109048 , nci_institute_code:  "TX340" , name: "Neurosurgery Institute of South Texas"], primaryKey: false)
		insert('organizations', [id: 109049 , nci_institute_code:  "TX341" , name: "Texas Oncology- San Marcos"], primaryKey: false)
		insert('organizations', [id: 109050 , nci_institute_code:  "TX342" , name: "Las Colinas Cancer Center"], primaryKey: false)
		insert('organizations', [id: 109051 , nci_institute_code:  "TX343" , name: "Texas Oncology-Austin North"], primaryKey: false)
		insert('organizations', [id: 109052 , nci_institute_code:  "TX344" , name: "Texas Oncology-Denton South"], primaryKey: false)
		insert('organizations', [id: 109053 , nci_institute_code:  "TX345" , name: "Pediatric Neurosurgery Center of Central Texas"], primaryKey: false)
		insert('organizations', [id: 109054 , nci_institute_code:  "TX346" , name: "Strictly Pediatrics Subspecialty Center"], primaryKey: false)
		insert('organizations', [id: 109055 , nci_institute_code:  "TX347" , name: "Texas Oncology-Arlington South"], primaryKey: false)
		insert('organizations', [id: 109056 , nci_institute_code:  "TX348" , name: "Radiology Consultants of North Dallas"], primaryKey: false)
		insert('organizations', [id: 109057 , nci_institute_code:  "TX349" , name: "Texas Oncology-Seton Williamson"], primaryKey: false)
		insert('organizations', [id: 109058 , nci_institute_code:  "TX350" , name: "Valmed Home Health Solutions-Amarillo"], primaryKey: false)
		insert('organizations', [id: 109059 , nci_institute_code:  "TX351" , name: "Central Texas Neruosurgery For Children"], primaryKey: false)
		insert('organizations', [id: 109060 , nci_institute_code:  "TX352" , name: "Texas Oncology Seton Northwest"], primaryKey: false)
		insert('organizations', [id: 109061 , nci_institute_code:  "TX353" , name: "Texas Oncology-Cedar Park"], primaryKey: false)
	}
	
	void m2(){
		insert('organizations', [id: 109062 , nci_institute_code:  "TX354" , name: "Austin Cancer Centers-Central Austin"], primaryKey: false)
		insert('organizations', [id: 109063 , nci_institute_code:  "TX355" , name: "Scott and White College Station Clinic"], primaryKey: false)
		insert('organizations', [id: 109064 , nci_institute_code:  "TX356" , name: "Amarillo Pathology Associates Limited"], primaryKey: false)
		insert('organizations', [id: 109065 , nci_institute_code:  "TX357" , name: "Greehey Children's Cancer Research Institute"], primaryKey: false)
		insert('organizations', [id: 109066 , nci_institute_code:  "TX358" , name: "Plano Cancer Institute"], primaryKey: false)
		insert('organizations', [id: 109067 , nci_institute_code:  "TX359" , name: "High Plains Radiology Association"], primaryKey: false)
		insert('organizations', [id: 109068 , nci_institute_code:  "TX360" , name: "Carl Ray Darnall Army Medical Center"], primaryKey: false)
		insert('organizations', [id: 109069 , nci_institute_code:  "TX361" , name: "Pediatric Blood and Marrow Stem Cell Transplant Clinic"], primaryKey: false)
		insert('organizations', [id: 109070 , nci_institute_code:  "TX362" , name: "Northwest Radiation Oncology-Cancer Center"], primaryKey: false)
		insert('organizations', [id: 109071 , nci_institute_code:  "TX363" , name: "Texas Oncology-Grapevine"], primaryKey: false)
		insert('organizations', [id: 109072 , nci_institute_code:  "TX364" , name: "Austin Cancer Centers-North"], primaryKey: false)
		insert('organizations', [id: 109073 , nci_institute_code:  "TX365" , name: "Plaza Cancer Specialists"], primaryKey: false)
		insert('organizations', [id: 109074 , nci_institute_code:  "TX366" , name: "Scott and White Cancer Research Institute"], primaryKey: false)
		insert('organizations', [id: 109075 , nci_institute_code:  "TX367" , name: "Cancer Care Centers of South Texas-Kerrville"], primaryKey: false)
		insert('organizations', [id: 109076 , nci_institute_code:  "TX368" , name: "McAllen Surgeons LLP"], primaryKey: false)
		insert('organizations', [id: 109077 , nci_institute_code:  "TX369" , name: "McAllen Surgeons LLP-Edinburg"], primaryKey: false)
		insert('organizations', [id: 109078 , nci_institute_code:  "TX370" , name: "Elizabeth Bonefas MD PA"], primaryKey: false)
		insert('organizations', [id: 109079 , nci_institute_code:  "TX371" , name: "Surgical Associates of Austin PA-Central Office"], primaryKey: false)
		insert('organizations', [id: 109080 , nci_institute_code:  "TX372" , name: "Texas Oncology-Lewisville"], primaryKey: false)
		insert('organizations', [id: 109081 , nci_institute_code:  "TX373" , name: "Texas Oncology-Kyle Hays"], primaryKey: false)
		insert('organizations', [id: 109082 , nci_institute_code:  "TX374" , name: "Excel Diagnostic Imaging Clinic at Westchase"], primaryKey: false)
		insert('organizations', [id: 109083 , nci_institute_code:  "TX375" , name: "Medical Therapy and Research PLLC"], primaryKey: false)
		insert('organizations', [id: 109084 , nci_institute_code:  "TX376" , name: "The MD Anderson Regional Care Center in The Woodlands"], primaryKey: false)
		insert('organizations', [id: 109085 , nci_institute_code:  "TX377" , name: "Seton Family of Doctors at Hays"], primaryKey: false)
		insert('organizations', [id: 109086 , nci_institute_code:  "TX378" , name: "Leading Edge Research PA"], primaryKey: false)
	}
	
	void m3(){
		insert('organizations', [id: 109087 , nci_institute_code:  "TX379" , name: "Children's Surgical Associates of West Texas"], primaryKey: false)
		insert('organizations', [id: 109088 , nci_institute_code:  "TX380" , name: "Medical Clinic of Houston LLP"], primaryKey: false)
		insert('organizations', [id: 109089 , nci_institute_code:  "TX381" , name: "Texas Oncology-Arlington North"], primaryKey: false)
		insert('organizations', [id: 109090 , nci_institute_code:  "TX382" , name: "Texas Oncology-Plano West"], primaryKey: false)
		insert('organizations', [id: 109091 , nci_institute_code:  "TX383" , name: "DAVA Oncology LP"], primaryKey: false)
		insert('organizations', [id: 109092 , nci_institute_code:  "TX384" , name: "State of the Heart Cardiology"], primaryKey: false)
		insert('organizations', [id: 109093 , nci_institute_code:  "TX385" , name: "Cardiovascular Surgical Associates Irving/Grapevine"], primaryKey: false)
		insert('organizations', [id: 109094 , nci_institute_code:  "TX386" , name: "Oncology Consultants PA-Medical Center (Cancer Center)"], primaryKey: false)
		insert('organizations', [id: 109095 , nci_institute_code:  "TX387" , name: "US Oncology Research LLC-The Woodlands"], primaryKey: false)
		insert('organizations', [id: 109096 , nci_institute_code:  "TX388" , name: "Texas Oncology-Weslaco"], primaryKey: false)
		insert('organizations', [id: 109097 , nci_institute_code:  "TX389" , name: "Cancer Center at Renaissance/ Doctors Hospital at Renaissance"], primaryKey: false)
		insert('organizations', [id: 109098 , nci_institute_code:  "TX390" , name: "Cancer Care Centers of South Texas-Metropolitan"], primaryKey: false)
		insert('organizations', [id: 109099 , nci_institute_code:  "TX391" , name: "Texas Oncology-Paris"], primaryKey: false)
		insert('organizations', [id: 109100 , nci_institute_code:  "TX392" , name: "Texas Oncology-Horizon Circle"], primaryKey: false)
		insert('organizations', [id: 109101 , nci_institute_code:  "TX393" , name: "Texas Oncology-Garland"], primaryKey: false)
		insert('organizations', [id: 109102 , nci_institute_code:  "TX394" , name: "Saint Luke's Diagnostic & Treatment Center - Kirby Glen"], primaryKey: false)
		insert('organizations', [id: 109103 , nci_institute_code:  "TX395" , name: "Clinical Pathology Associates"], primaryKey: false)
		insert('organizations', [id: 109104 , nci_institute_code:  "TX396" , name: "Cancer Care Centers of South Texas-New Braunfels"], primaryKey: false)
		insert('organizations', [id: 109105 , nci_institute_code:  "TX397" , name: "Texas Oncology-Flower Mound"], primaryKey: false)
		insert('organizations', [id: 109106 , nci_institute_code:  "TX398" , name: "Corpus Christi Precision Cancer Center"], primaryKey: false)
		insert('organizations', [id: 109107 , nci_institute_code:  "TX399" , name: "Austin Cancer Centers-Northwest"], primaryKey: false)
		insert('organizations', [id: 109108 , nci_institute_code:  "TX400" , name: "Katy Regional Care Center"], primaryKey: false)
		insert('organizations', [id: 109109 , nci_institute_code:  "TX401" , name: "Sugar Land Regional Care Center"], primaryKey: false)
		insert('organizations', [id: 109110 , nci_institute_code:  "TX402" , name: "UTMB Cancer Center at Victory Lakes"], primaryKey: false)
		insert('organizations', [id: 109111 , nci_institute_code:  "TX403" , name: "MD Anderson Cancer Center-Bay Area"], primaryKey: false)
	}
	
	void m4(){
		insert('organizations', [id: 109112 , nci_institute_code:  "TX404" , name: "Methodist Willowbrook Hospital"], primaryKey: false)
		insert('organizations', [id: 109113 , nci_institute_code:  "TX405" , name: "Texas Oncology-Southwest Fort Worth"], primaryKey: false)
		insert('organizations', [id: 109114 , nci_institute_code:  "TX406" , name: "Grace Clinic of Lubbock"], primaryKey: false)
		insert('organizations', [id: 109115 , nci_institute_code:  "TX407" , name: "Georgetown Cancer Center"], primaryKey: false)
		insert('organizations', [id: 109116 , nci_institute_code:  "TX408" , name: "Texas Oncology-The Woodlands"], primaryKey: false)
		insert('organizations', [id: 109117 , nci_institute_code:  "TX409" , name: "The Center for Cancer and Blood Disorders-Granbury"], primaryKey: false)
		insert('organizations', [id: 109118 , nci_institute_code:  "UT063" , name: "Cache Valley Cancer Treatment Center-Logan Regional Hospital"], primaryKey: false)
		insert('organizations', [id: 109119 , nci_institute_code:  "UT064" , name: "Regina Rosenthal MD"], primaryKey: false)
		insert('organizations', [id: 109120 , nci_institute_code:  "UT065" , name: "GammaWest Brachytherapy LLC-Saint George"], primaryKey: false)
		insert('organizations', [id: 109121 , nci_institute_code:  "UT066" , name: "Joesph D Te MD PC"], primaryKey: false)
		insert('organizations', [id: 109122 , nci_institute_code:  "VA171" , name: "Breast Care Specialists of Virginia PC"], primaryKey: false)
		insert('organizations', [id: 109123 , nci_institute_code:  "VA173" , name: "Virginia Cancer Specialists PC-Leesburg"], primaryKey: false)
		insert('organizations', [id: 109124 , nci_institute_code:  "VA175" , name: "Bon Secours Cancer Institute-Virginia Breast Center"], primaryKey: false)
		insert('organizations', [id: 109125 , nci_institute_code:  "VA176" , name: "Stark Oncology-Riverside Medical Group"], primaryKey: false)
		insert('organizations', [id: 109126 , nci_institute_code:  "VA177" , name: "Pediatric Surgical Associates of Northern Virginia"], primaryKey: false)
		insert('organizations', [id: 109127 , nci_institute_code:  "VA178" , name: "George Mason University-Prince William Campus"], primaryKey: false)
		insert('organizations', [id: 109128 , nci_institute_code:  "VA179" , name: "Johnston Memorial Cancer Center"], primaryKey: false)
		insert('organizations', [id: 109129 , nci_institute_code:  "VA180" , name: "The Fairfax MRI Center"], primaryKey: false)
		insert('organizations', [id: 109130 , nci_institute_code:  "VA181" , name: "Virginia Physicians Incorporated-Glen Allen"], primaryKey: false)
		insert('organizations', [id: 109131 , nci_institute_code:  "VA182" , name: "Virginia Oncology Associates-Chesapeake"], primaryKey: false)
		insert('organizations', [id: 109132 , nci_institute_code:  "VA183" , name: "Virginia Polytechnic Institute and State University"], primaryKey: false)
		insert('organizations', [id: 109133 , nci_institute_code:  "VA184" , name: "Hematology Oncology Patient Enterprises PC"], primaryKey: false)
		insert('organizations', [id: 109134 , nci_institute_code:  "VA185" , name: "Fort Belvoir Community Hospital"], primaryKey: false)
		insert('organizations', [id: 109135 , nci_institute_code:  "VA186" , name: "Bon Secours Virginia Breast Center"], primaryKey: false)
		insert('organizations', [id: 109136 , nci_institute_code:  "VA187" , name: "Shenandoah Valley Surgical Associates Inc"], primaryKey: false)
	}
	
	void m5(){
		insert('organizations', [id: 109137 , nci_institute_code:  "VA188" , name: "Augusta Health Cancer Center"], primaryKey: false)
		insert('organizations', [id: 109138 , nci_institute_code:  "VA189" , name: "Kaiser Permanente Tysons Corner Medical Center"], primaryKey: false)
		insert('organizations', [id: 109139 , nci_institute_code:  "VA190" , name: "Kaiser Permanente-Burke Medical Center"], primaryKey: false)
		insert('organizations', [id: 109140 , nci_institute_code:  "VA191" , name: "Hope Cancer Care Charlottesville"], primaryKey: false)
		insert('organizations', [id: 109141 , nci_institute_code:  "VA192" , name: "Virginia Gynecologic Oncology"], primaryKey: false)
		insert('organizations', [id: 109142 , nci_institute_code:  "VA193" , name: "Peninsula Cancer Institute-Cancer Specialists of Tidewater"], primaryKey: false)
		insert('organizations', [id: 109143 , nci_institute_code:  "VA194" , name: "Tidewater Surgical Specialists-Harbour View"], primaryKey: false)
		insert('organizations', [id: 109144 , nci_institute_code:  "VA195" , name: "Sentara Princess Anne Hospital"], primaryKey: false)
		insert('organizations', [id: 109145 , nci_institute_code:  "VA196" , name: "Sentara Leigh Hospital"], primaryKey: false)
		insert('organizations', [id: 109146 , nci_institute_code:  "VA197" , name: "Sentara Obici Hospital"], primaryKey: false)
		insert('organizations', [id: 109147 , nci_institute_code:  "VA198" , name: "Sentara Williamsburg Regional Medical Center"], primaryKey: false)
		insert('organizations', [id: 109148 , nci_institute_code:  "VT031" , name: "National Life Cancer Treatment Center"], primaryKey: false)
		insert('organizations', [id: 109149 , nci_institute_code:  "WA178" , name: "Seattle Neuroscience Institute"], primaryKey: false)
		insert('organizations', [id: 109150 , nci_institute_code:  "WA179" , name: "Legacy Salmon Creek Hospital"], primaryKey: false)
		insert('organizations', [id: 109151 , nci_institute_code:  "WA180" , name: "Inland Neurosurgery and Spine Associates"], primaryKey: false)
		insert('organizations', [id: 109152 , nci_institute_code:  "WA181" , name: "Harrison Poulsbo Hematology and Oncology"], primaryKey: false)
		insert('organizations', [id: 109153 , nci_institute_code:  "WA182" , name: "Seattle Prostate Cancer Center"], primaryKey: false)
		insert('organizations', [id: 109154 , nci_institute_code:  "WA183" , name: "Franciscan Research Center-Northwest Medical Plaza"], primaryKey: false)
		insert('organizations', [id: 109155 , nci_institute_code:  "WA184" , name: "Cancer Care Center at Island Hospital"], primaryKey: false)
		insert('organizations', [id: 109156 , nci_institute_code:  "WA185" , name: "Overlake Internal Medicine Associates"], primaryKey: false)
		insert('organizations', [id: 109157 , nci_institute_code:  "WA186" , name: "North Puget Oncology Clinic"], primaryKey: false)
		insert('organizations', [id: 109158 , nci_institute_code:  "WA187" , name: "MultiCare Gig Harbor Medical Park"], primaryKey: false)
		insert('organizations', [id: 109159 , nci_institute_code:  "WA188" , name: "Western Washington Medical Group"], primaryKey: false)
		insert('organizations', [id: 109160 , nci_institute_code:  "WA189" , name: "The Doctors Clinic"], primaryKey: false)
		insert('organizations', [id: 109161 , nci_institute_code:  "WA190" , name: "Robert R Witham MD Inc PS"], primaryKey: false)
	}
	
	void m6(){
		insert('organizations', [id: 109162 , nci_institute_code:  "WA191" , name: "Tacoma/Valley Radiation Oncology Centers-Saint Joe's"], primaryKey: false)
		insert('organizations', [id: 109163 , nci_institute_code:  "WA192" , name: "Tacoma/Valley Radiation Oncology Centers-Puyallup"], primaryKey: false)
		insert('organizations', [id: 109164 , nci_institute_code:  "WA193" , name: "Tacoma/Valley Radiation Oncology Centers-Gig Harbor"], primaryKey: false)
		insert('organizations', [id: 109165 , nci_institute_code:  "WA194" , name: "Kaiser Permanente-Cascade Park"], primaryKey: false)
		insert('organizations', [id: 109166 , nci_institute_code:  "WA196" , name: "Swedish Cancer Institute-Issaquah"], primaryKey: false)
		insert('organizations', [id: 109167 , nci_institute_code:  "WA197" , name: "Northwest Cancer Clinic"], primaryKey: false)
		insert('organizations', [id: 109168 , nci_institute_code:  "WA198" , name: "Osborn Cancer Care"], primaryKey: false)
		insert('organizations', [id: 109169 , nci_institute_code:  "WI173" , name: "Sursum Corda SC"], primaryKey: false)
		insert('organizations', [id: 109170 , nci_institute_code:  "WI174" , name: "Surgical Associates SC"], primaryKey: false)
		insert('organizations', [id: 109171 , nci_institute_code:  "WI175" , name: "WiCell Research Institute"], primaryKey: false)
		insert('organizations', [id: 109172 , nci_institute_code:  "WI176" , name: "Marshfield Clinic Cancer Care at Saint Michael's Hospital"], primaryKey: false)
		insert('organizations', [id: 109173 , nci_institute_code:  "WI177" , name: "Aurora Thoracic Surgery"], primaryKey: false)
		insert('organizations', [id: 109174 , nci_institute_code:  "WI179" , name: "Aurora Cancer Care-Racine"], primaryKey: false)
		insert('organizations', [id: 109175 , nci_institute_code:  "WI180" , name: "Aurora Cancer Care-Burlington"], primaryKey: false)
		insert('organizations', [id: 109176 , nci_institute_code:  "WI181" , name: "Aurora Advanced Healthcare Inc-Mequon"], primaryKey: false)
		insert('organizations', [id: 109177 , nci_institute_code:  "WI182" , name: "Aurora Cancer Care-Waukesha"], primaryKey: false)
		insert('organizations', [id: 109178 , nci_institute_code:  "WI183" , name: "Aurora Cancer Care-Milwaukee"], primaryKey: false)
		insert('organizations', [id: 109179 , nci_institute_code:  "WI184" , name: "Aurora Advanced Healthcare Inc-Menomonee Falls"], primaryKey: false)
		insert('organizations', [id: 109180 , nci_institute_code:  "WI185" , name: "The Bellin Cancer Team of Bellin Health"], primaryKey: false)
		insert('organizations', [id: 109181 , nci_institute_code:  "WI186" , name: "Aurora Medical Center in Summit"], primaryKey: false)
		insert('organizations', [id: 109182 , nci_institute_code:  "WI187" , name: "Wheaton Franciscan-The Wisconsin Heart Hospital"], primaryKey: false)
		insert('organizations', [id: 109183 , nci_institute_code:  "WI188" , name: "Mayo Clinic Health System-Luther Campus"], primaryKey: false)
		insert('organizations', [id: 109184 , nci_institute_code:  "WI189" , name: "BloodCenter of Wisconsin"], primaryKey: false)
		insert('organizations', [id: 109185 , nci_institute_code:  "WI191" , name: "Waukesha Surgical Specialists"], primaryKey: false)
		insert('organizations', [id: 109186 , nci_institute_code:  "WI192" , name: "Matthews Oncology Associates"], primaryKey: false)
	}
	
	void m7(){
		insert('organizations', [id: 109187 , nci_institute_code:  "WI193" , name: "Wisconsin Heart and Vascular Institute-Main Office"], primaryKey: false)
		insert('organizations', [id: 109188 , nci_institute_code:  "WI194" , name: "Aurora Cancer Care-Grafton"], primaryKey: false)
		insert('organizations', [id: 109189 , nci_institute_code:  "WI195" , name: "Saint Vincent Hospital's Pediatric Center"], primaryKey: false)
		insert('organizations', [id: 109190 , nci_institute_code:  "WI196" , name: "Westfields Hospital/Cancer Center of Western Wisconsin"], primaryKey: false)
		insert('organizations', [id: 109191 , nci_institute_code:  "WI198" , name: "Radiation Oncology Associates Limited"], primaryKey: false)
		insert('organizations', [id: 109192 , nci_institute_code:  "WV051" , name: "University of Charleston"], primaryKey: false)
		insert('organizations', [id: 109193 , nci_institute_code:  "WV054" , name: "Radiology Incorporated"], primaryKey: false)
		insert('organizations', [id: 109194 , nci_institute_code:  "WV055" , name: "Primary Oncology Network"], primaryKey: false)
		insert('organizations', [id: 109195 , nci_institute_code:  "WV057" , name: "Gateway Hematology Oncology"], primaryKey: false)
		insert('organizations', [id: 109196 , nci_institute_code:  "WV058" , name: "Associated Radiologists Inc"], primaryKey: false)
		insert('organizations', [id: 109197 , nci_institute_code:  "WY017" , name: "Riverton Memorial Hospital"], primaryKey: false)
		insert('organizations', [id: 109198 , nci_institute_code:  "WY018" , name: "Wind River Clinic"], primaryKey: false)
		insert('organizations', [id: 109199 , nci_institute_code:  "CCR" , name: "Center for Cancer Research"], primaryKey: false)
		insert('organizations', [id: 109200 , nci_institute_code:  "CTEP" , name: "Cancer Therapy Evaluation Program"], primaryKey: false)
		insert('organizations', [id: 109201 , nci_institute_code:  "DCB" , name: "Division of Cancer Biology"], primaryKey: false)
		insert('organizations', [id: 109202 , nci_institute_code:  "DCCPS" , name: "Division of Cancer Control and Population Sciences"], primaryKey: false)
		insert('organizations', [id: 109203 , nci_institute_code:  "DCEG" , name: "Division of Cancer Epidemiology and Genetics"], primaryKey: false)
		insert('organizations', [id: 109204 , nci_institute_code:  "DTP" , name: "Developmental Therapeutics Program"], primaryKey: false)
		insert('organizations', [id: 109205 , nci_institute_code:  "DCP" , name: "Division of Cancer Prevention"], primaryKey: false)
		insert('organizations', [id: 109206 , nci_institute_code:  "DEA" , name: "Division of Extramural Activities"], primaryKey: false)
		insert('organizations', [id: 109207 , nci_institute_code:  "OD" , name: "Office of the Director"], primaryKey: false)
		insert('organizations', [id: 109208 , nci_institute_code:  "OSB/SPOREs" , name: "Organ Systems Branch (OSB) /Specialized Programs of Research Excellence (SPOREs)"], primaryKey: false)
		insert('organizations', [id: 109209 , nci_institute_code:  "CIP" , name: "Cancer Imaging Program"], primaryKey: false)
		insert('organizations', [id: 109210 , nci_institute_code:  "CDP" , name: "Cancer Diagnosis Program"], primaryKey: false)
		insert('organizations', [id: 109211 , nci_institute_code:  "TRP" , name: "Translational Research Program"], primaryKey: false)
	}
	
	void m8(){
		insert('organizations', [id: 109212 , nci_institute_code:  "RRP" , name: "Radiation Research Program"], primaryKey: false)
		insert('organizations', [id: 109213 , nci_institute_code:  "NEI" , name: "National Eye Institute"], primaryKey: false)
		insert('organizations', [id: 109214 , nci_institute_code:  "NHGRI" , name: "National Human Genome Research Institute"], primaryKey: false)
		insert('organizations', [id: 109215 , nci_institute_code:  "NIA" , name: "National Institute on Aging"], primaryKey: false)
		insert('organizations', [id: 109216 , nci_institute_code:  "NIAAA" , name: "National Institute on Alcohol Abuse and Alcoholism"], primaryKey: false)
		insert('organizations', [id: 109217 , nci_institute_code:  "NIBIB" , name: "National Institute of Biomedical Imaging and Bioengineering"], primaryKey: false)
		insert('organizations', [id: 109218 , nci_institute_code:  "NICHD" , name: "Eunice Kennedy Shriver National Institute of Child Health and Human Development"], primaryKey: false)
		insert('organizations', [id: 109219 , nci_institute_code:  "NIDCR" , name: "National Institute of Dental and Craniofacial Research"], primaryKey: false)
		insert('organizations', [id: 109220 , nci_institute_code:  "NIDDK" , name: "National Institute of Diabetes and Digestive and Kidney Diseases"], primaryKey: false)
		insert('organizations', [id: 109221 , nci_institute_code:  "NIDA" , name: "National Institute on Drug Abuse"], primaryKey: false)
		insert('organizations', [id: 109222 , nci_institute_code:  "NIEHS" , name: "National Institute of Environmental Health Sciences"], primaryKey: false)
		insert('organizations', [id: 109223 , nci_institute_code:  "NIGMS" , name: "National Institute of General Medical Sciences"], primaryKey: false)
		insert('organizations', [id: 109224 , nci_institute_code:  "NIMH" , name: "National Institute of Mental Health"], primaryKey: false)
		insert('organizations', [id: 109225 , nci_institute_code:  "NINR" , name: "National Institute of Nursing Research"], primaryKey: false)
		insert('organizations', [id: 109226 , nci_institute_code:  "NLM" , name: "National Library of Medicine"], primaryKey: false)
		insert('organizations', [id: 109227 , nci_institute_code:  "CIT" , name: "Center for Information Technology"], primaryKey: false)
		insert('organizations', [id: 109228 , nci_institute_code:  "CSR" , name: "Center for Scientific Review"], primaryKey: false)
		insert('organizations', [id: 109229 , nci_institute_code:  "FIC" , name: "John E. Fogarty International Center for Advanced Study in the Health Sciences"], primaryKey: false)
		insert('organizations', [id: 109230 , nci_institute_code:  "NCCAM" , name: "National Center for Complementary and Alternative Medicine"], primaryKey: false)
		insert('organizations', [id: 109231 , nci_institute_code:  "NCMHD" , name: "National Center on Minority Health and Health Disparities"], primaryKey: false)
		insert('organizations', [id: 109232 , nci_institute_code:  "NCRR" , name: "National Center for Research Resources"], primaryKey: false)
		insert('organizations', [id: 109233 , nci_institute_code:  "CC" , name: "NIH Clinical Center"], primaryKey: false)
		insert('organizations', [id: 109234 , nci_institute_code:  "CDER" , name: "Center for Drug Evaluation and Research"], primaryKey: false)
		insert('organizations', [id: 109235 , nci_institute_code:  "CBER" , name: "Center for Biologics Evaluation and Research"], primaryKey: false)
		insert('organizations', [id: 109236 , nci_institute_code:  "CDRH" , name: "Center for Devices and Radiological Health"], primaryKey: false)
	}
	
	void m9(){
		insert('organizations', [id: 109237 , nci_institute_code:  "ACOSOG" , name: "American College of Surgeons Oncology Trials Group"], primaryKey: false)
		insert('organizations', [id: 109238 , nci_institute_code:  "ECOG" , name: "Eastern Cooperative Oncology Group"], primaryKey: false)
		insert('organizations', [id: 109239 , nci_institute_code:  "GOG" , name: "Gynecologic Oncology Group"], primaryKey: false)
		insert('organizations', [id: 109240 , nci_institute_code:  "NCCTG" , name: "North Central Cancer Treatment Group"], primaryKey: false)
		insert('organizations', [id: 109241 , nci_institute_code:  "NCIC" , name: "National Cancer Institute of Canada Clinical Trials Group"], primaryKey: false)
		insert('organizations', [id: 109242 , nci_institute_code:  "NSABP" , name: "National Surgical Adjuvant Breast and Bowel Project"], primaryKey: false)
		insert('organizations', [id: 109243 , nci_institute_code:  "SWOG" , name: "Southwest Oncology Group"], primaryKey: false)
		insert('organizations', [id: 109244 , nci_institute_code:  "COG" , name: "Children's Oncology Group"], primaryKey: false)
		insert('organizations', [id: 109245 , nci_institute_code:  "ACCRU" , name: "Academic and Community Cancer Research United"], primaryKey: false)
		insert('organizations', [id: 109246 , nci_institute_code:  "ALLIANCE" , name: "Alliance for Clinical Trials in Oncology"], primaryKey: false)
		insert('organizations', [id: 109247 , nci_institute_code:  "NRG" , name: "NRG Oncology Group"], primaryKey: false)
   }
   
    void down() {
	execute("DELETE from organizations where id >= 109012 and id < 109248")
  }
    
}