class UpdateExistingOrganizations extends edu.northwestern.bioinformatics.bering.Migration {

 void up() {
 		m0()
		m1()
		m2()
		m3()
		m4()
		m5()
		m6()
		m7()
		m8()
		m9()
		m10()
		m11()
		m12()
		m13()
		m14()
		m15()
		m16()
		m17()
		m18()
		m19()
		m20()
		m21()
		m22()
		m23()
		m24()
		m25()
		m26()
		m27()
		m28()
		m29()
		m30()
 }
  
	void m0(){
		execute("update organizations set name = 'Newcastle Private Hospital' where nci_institute_code = '03023'")
		execute("update organizations set name = 'Royal Childrens Hospital-Brisbane' where nci_institute_code = '03028'")
		execute("update organizations set name = 'Bankstown-Lidcombe Hospital' where nci_institute_code = '03075'")
		execute("update organizations set name = 'Monash Medical Centre Moorabbin Campus' where nci_institute_code = '03106'")
		execute("update organizations set name = 'Saint John of God Hospital - Bunbury' where nci_institute_code = '03121'")
		execute("update organizations set name = 'Haematology and Oncology Clinics of Australia' where nci_institute_code = '03126'")
		execute("update organizations set name = 'UZ Leuven-University Hospital Gasthuisberg' where nci_institute_code = '06018'")
		execute("update organizations set name = 'Centre Hospitalier Regional de la Citadelle' where nci_institute_code = '06029'")
		execute("update organizations set name = 'Instituto Nacional De Cancer Brazil' where nci_institute_code = '08020'")
		execute("update organizations set name = 'Specialty Clinic College of Medicine of ABC-Santo Andre' where nci_institute_code = '08030'")
		execute("update organizations set name = 'The Montreal Children\\'s Hospital of the MUHC' where nci_institute_code = '11001'")
		execute("update organizations set name = 'Royal Victoria Hospital' where nci_institute_code = '11002'")
		execute("update organizations set name = 'CHA Hopital L\\'Enfant-Jesus' where nci_institute_code = '11004'")
		execute("update organizations set name = 'QEII Health Sciences Centre/Capital District Health Authority' where nci_institute_code = '11008'")
		execute("update organizations set name = 'Niagara Health System-Saint Catharines General' where nci_institute_code = '11016'")
		execute("update organizations set name = 'Royal Victoria Regional Health Centre' where nci_institute_code = '11019'")
		execute("update organizations set name = 'Horizon Health Network-Saint John Regional Hospital' where nci_institute_code = '11035'")
		execute("update organizations set name = 'Centre Hospitalier Des Vallees De L\\’Outaouais' where nci_institute_code = '11038'")
		execute("update organizations set name = 'Vancouver General Hospital-Gordon and Leslie Diamond Health Care Centre' where nci_institute_code = '11054'")
		execute("update organizations set name = 'Centre Hospitalier Universitaire de Sherbrooke-Fleurimont' where nci_institute_code = '11065'")
		execute("update organizations set name = 'CSSS Champlain-Charles Le Moyne' where nci_institute_code = '11069'")
		execute("update organizations set name = 'CHU de Quebec' where nci_institute_code = '11074'")
		execute("update organizations set name = 'BCCA-Vancouver Cancer Centre' where nci_institute_code = '11081'")
		execute("update organizations set name = 'Saint Joseph\\'s Healthcare Charlton Campus' where nci_institute_code = '11083'")
		execute("update organizations set name = 'Children\\'s Hospital' where nci_institute_code = '11101'")
	}
	
	void m1(){
		execute("update organizations set name = 'Le Centre hospitalier affilie universitaire de Quebec-Saint Sacrement' where nci_institute_code = '11110'")
		execute("update organizations set name = 'The Vitalite Health Network - Dr Leon Richard Oncology Centre' where nci_institute_code = '11111'")
		execute("update organizations set name = 'Chedoke Hospital at Hamilton Health Sciences' where nci_institute_code = '11117'")
		execute("update organizations set name = 'University Institute of Cardiology and Pneumology of Quebec (Laval Hospital)' where nci_institute_code = '11123'")
		execute("update organizations set name = 'Centre Hospitalier Universitaire de Sherbrooke (CHUS)' where nci_institute_code = '11125'")
		execute("update organizations set name = 'Centre Hospitalier Universitaire Sainte-Justine' where nci_institute_code = '11147'")
		execute("update organizations set name = 'Health Sciences North' where nci_institute_code = '11153'")
		execute("update organizations set name = 'William Osler Health System-Brampton Civic Hospital' where nci_institute_code = '11162'")
		execute("update organizations set name = 'Centre Hospitalier Régional de Lanaudière' where nci_institute_code = '11165'")
		execute("update organizations set name = 'Centre Hospitalier Regional de Rimouski' where nci_institute_code = '11170'")
		execute("update organizations set name = 'Burnaby Hospital-Regional Cancer Center' where nci_institute_code = '11189'")
		execute("update organizations set name = 'Stronach Regional Health Centre at Southlake' where nci_institute_code = '11190'")
		execute("update organizations set name = 'Hamilton and District Urology Association McMaster Institute' where nci_institute_code = '11204'")
		execute("update organizations set name = 'London Health Sciences Centre-Corporate' where nci_institute_code = '11208'")
		execute("update organizations set name = 'London Health Sciences Centre-South Street' where nci_institute_code = '11227'")
		execute("update organizations set name = 'Health Quality Ontario' where nci_institute_code = '11261'")
		execute("update organizations set name = 'Walker Family Cancer Centre' where nci_institute_code = '11277'")
		execute("update organizations set name = 'Margery E Yuill Cancer Centre' where nci_institute_code = '11290'")
		execute("update organizations set name = 'BCCA-Abbotsford Cancer Centre' where nci_institute_code = '11297'")
		execute("update organizations set name = 'Luis Calvo Mackenna Hospital' where nci_institute_code = '14002'")
		execute("update organizations set name = 'National Cancer Institute - Slovakia Republic' where nci_institute_code = '18004'")
		execute("update organizations set name = 'Hôpital La Pitié-Salpétrière' where nci_institute_code = '28002'")
		execute("update organizations set name = 'Institut Gustave Roussy' where nci_institute_code = '28011'")
		execute("update organizations set name = 'Hospital Claude Huriez Chru' where nci_institute_code = '28079'")
		execute("update organizations set name = 'Institut National de la Santé et de la Recherche Médicale' where nci_institute_code = '28113'")
	}
	
	void m2(){
		execute("update organizations set name = 'Chinese University of Hong Kong-Prince of Wales Hospital' where nci_institute_code = '34003'")
		execute("update organizations set name = 'Royal Victoria Hospital' where nci_institute_code = '39001'")
		execute("update organizations set name = 'Saint Lukes Hospital' where nci_institute_code = '39003'")
		execute("update organizations set name = 'Saint Finbarr\\'s Hospital' where nci_institute_code = '39005'")
		execute("update organizations set name = 'Mater Private Hospital' where nci_institute_code = '39015'")
		execute("update organizations set name = 'L\\’Ospedale Pediatrico Bambino Gesù' where nci_institute_code = '41053'")
		execute("update organizations set name = 'Università di Cagliari' where nci_institute_code = '41067'")
		execute("update organizations set name = 'University of the Ryukyus Hospital-Col Health Scnc' where nci_institute_code = '42002'")
		execute("update organizations set name = 'Keio University-Shinanomachi Campus (Hospital)' where nci_institute_code = '42043'")
		execute("update organizations set name = 'Catholic University of Korea-Seoul Saint Mary\\'s Hospital' where nci_institute_code = '43003'")
		execute("update organizations set name = 'Korean Cancer Study Group' where nci_institute_code = '43005'")
		execute("update organizations set name = 'Gangnam Severance Hospital' where nci_institute_code = '43007'")
		execute("update organizations set name = 'Kyungpook National University Hospital' where nci_institute_code = '43011'")
		execute("update organizations set name = 'Hospital Infantil de Mexico Federico Gomez' where nci_institute_code = '48001'")
		execute("update organizations set name = 'VU University Medical Center' where nci_institute_code = '51003'")
		execute("update organizations set name = 'Vrije Universiteit Medisch Centrum' where nci_institute_code = '51005'")
		execute("update organizations set name = 'Hospital Nacional Hipólito Unanue' where nci_institute_code = '55002'")
		execute("update organizations set name = 'Fudan University Shanghai Cancer Center' where nci_institute_code = '60005'")
		execute("update organizations set name = 'University of Witwatersrand' where nci_institute_code = '63003'")
		execute("update organizations set name = 'Hospital Clinic i Provincial' where nci_institute_code = '65003'")
		execute("update organizations set name = 'Hospital Nuestra Senora de Aranzazu' where nci_institute_code = '65013'")
		execute("update organizations set name = 'Instituto Valenciano de Oncologia' where nci_institute_code = '65016'")
		execute("update organizations set name = 'Örebro University Hospital' where nci_institute_code = '66012'")
		execute("update organizations set name = 'Kantonsspital Aarau AG-Canton Hospital' where nci_institute_code = '67029'")
		execute("update organizations set name = 'Hacettepe Üniversitesi Tip Fakültesi' where nci_institute_code = '69001'")
	}
	
	void m3(){	
		execute("update organizations set name = 'UniversitaetsKlinikum Heidelberg-Kopfklinik' where nci_institute_code = '76088'")
		execute("update organizations set name = 'Veterans Administration Medical Center-Tuscaloosa' where nci_institute_code = 'AL053'")
		execute("update organizations set name = 'Mercy Hospital Fort Smith' where nci_institute_code = 'AR012'")
		execute("update organizations set name = 'NEA Baptist Clinic-Matthews' where nci_institute_code = 'AR019'")
		execute("update organizations set name = 'CARTI /Little Rock Hematology and Oncology' where nci_institute_code = 'AR020'")
		execute("update organizations set name = 'Highlands Oncology Group' where nci_institute_code = 'AR029'")
		execute("update organizations set name = 'Mercy Cancer Center-Hot Springs' where nci_institute_code = 'AR043'")
		execute("update organizations set name = 'NEA Baptist Memorial Hospital' where nci_institute_code = 'AR047'")
		execute("update organizations set name = 'Saint Joseph\\'s Hospital and Medical Center' where nci_institute_code = 'AZ009'")
		execute("update organizations set name = 'The University of Arizona Medical Center-University Campus' where nci_institute_code = 'AZ017'")
		execute("update organizations set name = 'Mayo Clinic in Arizona' where nci_institute_code = 'AZ020'")
		execute("update organizations set name = 'Arizona Oncology Associates-Craycroft' where nci_institute_code = 'AZ030'")
		execute("update organizations set name = 'Valley Radiology Oncology Limited' where nci_institute_code = 'AZ039'")
		execute("update organizations set name = 'Ironwood Cancer and Research Centers-Broadway' where nci_institute_code = 'AZ042'")
		execute("update organizations set name = 'Palo Verde Cancer Specialists' where nci_institute_code = 'AZ047'")
		execute("update organizations set name = 'Banner Sun Health Research Institute' where nci_institute_code = 'AZ085'")
		execute("update organizations set name = 'Barrow Neurological Institute' where nci_institute_code = 'AZ086'")
		execute("update organizations set name = 'Oncogyne PC-Arizona Oncology' where nci_institute_code = 'AZ094'")
		execute("update organizations set name = 'Pinnacle Oncology Associates' where nci_institute_code = 'AZ103'")
		execute("update organizations set name = 'Cardon Children\\'s Medical Center' where nci_institute_code = 'AZ105'")
		execute("update organizations set name = 'Ironwood Cancer and Research Centers-Dobson' where nci_institute_code = 'AZ106'")
		execute("update organizations set name = 'Arizona Center for Cancer Care-Glendale' where nci_institute_code = 'AZ108'")
		execute("update organizations set name = 'The University of Arizona Cancer Center-North Campus' where nci_institute_code = 'AZ110'")
		execute("update organizations set name = 'Ironwood Cancer and Research Centers-Mesa' where nci_institute_code = 'AZ113'")
		execute("update organizations set name = 'University of California at Los Angeles Health System' where nci_institute_code = 'CA006'")
	}
	
	void m4(){
		execute("update organizations set name = 'Los Angeles County-USC Medical Center' where nci_institute_code = 'CA012'")
		execute("update organizations set name = 'Kaiser Permanente-Bellflower' where nci_institute_code = 'CA031'")
		execute("update organizations set name = 'Veterans Administration-San Diego Medical Center' where nci_institute_code = 'CA070'")
		execute("update organizations set name = 'Kaiser Permanente-Fontana' where nci_institute_code = 'CA077'")
		execute("update organizations set name = 'Kaiser Permanente-Anaheim' where nci_institute_code = 'CA095'")
		execute("update organizations set name = 'Sansum Clinic Inc' where nci_institute_code = 'CA098'")
		execute("update organizations set name = 'Saint Agnes Medical Center' where nci_institute_code = 'CA112'")
		execute("update organizations set name = 'San Francisco General Hospital' where nci_institute_code = 'CA125'")
		execute("update organizations set name = 'California Pacific Medical Center-Pacific Campus' where nci_institute_code = 'CA127'")
		execute("update organizations set name = 'UCSF-Mount Zion' where nci_institute_code = 'CA136'")
		execute("update organizations set name = 'Palo Alto Medical Foundation Health Care' where nci_institute_code = 'CA138'")
		execute("update organizations set name = 'Lucile Packard Children\\'s Hospital Stanford University' where nci_institute_code = 'CA139'")
		execute("update organizations set name = 'Stanford University Hospitals and Clinics' where nci_institute_code = 'CA141'")
		execute("update organizations set name = 'Kaiser Permanente-Fremont' where nci_institute_code = 'CA148'")
		execute("update organizations set name = 'Kaiser Permanente Hayward' where nci_institute_code = 'CA150'")
		execute("update organizations set name = 'Alta Bates Summit Medical Center-Herrick Campus' where nci_institute_code = 'CA164'")
		execute("update organizations set name = 'University of California-Berkeley' where nci_institute_code = 'CA165'")
		execute("update organizations set name = 'University of California Davis-Cancer Center' where nci_institute_code = 'CA189'")
		execute("update organizations set name = 'Florence R Wheeler Cancer Center at Mercy Hospital' where nci_institute_code = 'CA225'")
		execute("update organizations set name = 'Kaiser Permanente-Fresno' where nci_institute_code = 'CA242'")
		execute("update organizations set name = 'UC San Diego Moores Cancer Center' where nci_institute_code = 'CA249'")
		execute("update organizations set name = 'Providence Little Company of Mary Medical Center Torrance' where nci_institute_code = 'CA250'")
		execute("update organizations set name = 'Sierra Nevada Memorial Hospital/Cancer Center' where nci_institute_code = 'CA253'")
		execute("update organizations set name = 'Sutter Western Cancer Research Group' where nci_institute_code = 'CA276'")
		execute("update organizations set name = 'Radiation Medical Group Inc' where nci_institute_code = 'CA287'")
	}
	
	void m5(){
		execute("update organizations set name = 'Kaiser Permanente-San Diego Mission' where nci_institute_code = 'CA306'")
		execute("update organizations set name = 'Kaiser Permanente-San Diego Zion' where nci_institute_code = 'CA332'")
		execute("update organizations set name = 'Kaiser Permanente-Woodland Hills' where nci_institute_code = 'CA370'")
		execute("update organizations set name = 'UCSF Medical Center-Parnassus' where nci_institute_code = 'CA385'")
		execute("update organizations set name = 'Kaiser Permanente-Riverside' where nci_institute_code = 'CA388'")
		execute("update organizations set name = 'Tower Hematology Oncology Medical Group' where nci_institute_code = 'CA431'")
		execute("update organizations set name = 'Kaiser Permanente-Baldwin Park' where nci_institute_code = 'CA454'")
		execute("update organizations set name = 'Keck Medical Center of USC' where nci_institute_code = 'CA471'")
		execute("update organizations set name = 'Kaiser Permanente-Cadillac' where nci_institute_code = 'CA512'")
		execute("update organizations set name = 'Hollywood Presbyterian Medical Center' where nci_institute_code = 'CA538'")
		execute("update organizations set name = 'Washington Radiation Oncology Center' where nci_institute_code = 'CA541'")
		execute("update organizations set name = 'Marin Cancer Care Inc' where nci_institute_code = 'CA551'")
		execute("update organizations set name = 'East Bay Medical Oncology Hematology Medical Associates Inc-Pleasant Hill' where nci_institute_code = 'CA552'")
		execute("update organizations set name = 'Sutter Solano Medical Center/Cancer Center' where nci_institute_code = 'CA559'")
		execute("update organizations set name = 'California Cancer Associates for Research and Excellence (cCare)' where nci_institute_code = 'CA621'")
		execute("update organizations set name = 'Newport Pacific Medical Associates' where nci_institute_code = 'CA648'")
		execute("update organizations set name = 'UCLA Healthcare-Santa Monica' where nci_institute_code = 'CA652'")
		execute("update organizations set name = 'Breast Care Specialists-Jane Kakkis MD' where nci_institute_code = 'CA667'")
		execute("update organizations set name = 'Pacific Cancer Care-Monterey' where nci_institute_code = 'CA675'")
		execute("update organizations set name = 'Hematology and Oncology Associates-Oakland' where nci_institute_code = 'CA692'")
		execute("update organizations set name = 'Kaiser Permanente-Irvine' where nci_institute_code = 'CA699'")
		execute("update organizations set name = 'Charles Wiseman MD FACP' where nci_institute_code = 'CA701'")
		execute("update organizations set name = 'Kaiser Permanente-Ontario' where nci_institute_code = 'CA726'")
		execute("update organizations set name = 'Mercy Cancer Center' where nci_institute_code = 'CA729'")
		execute("update organizations set name = 'Kaiser Permanente Cancer Treatment Center' where nci_institute_code = 'CA730'")
	}
	
	void m6(){
		execute("update organizations set name = 'Innovative Cancer Research Consortium at Glendale Adventist' where nci_institute_code = 'CA731'")
		execute("update organizations set name = 'Kaiser Permanente-Deer Valley Medical Center' where nci_institute_code = 'CA735'")
		execute("update organizations set name = 'Children\\'s Hospital Colorado' where nci_institute_code = 'CO011'")
		execute("update organizations set name = 'Saint Anthony Hospital' where nci_institute_code = 'CO031'")
		execute("update organizations set name = 'Kaiser Permanente-Franklin' where nci_institute_code = 'CO034'")
		execute("update organizations set name = 'Colorado Blood Cancer Institute' where nci_institute_code = 'CO055'")
		execute("update organizations set name = 'University of Colorado at Denver' where nci_institute_code = 'CO085'")
		execute("update organizations set name = 'Cancer Care and Hematology-Fort Collins' where nci_institute_code = 'CO089'")
		execute("update organizations set name = 'Bristol Hospital/Cancer Care Center' where nci_institute_code = 'CT001'")
		execute("update organizations set name = 'Veterans Affairs Connecticut Healthcare System-Newington Campus' where nci_institute_code = 'CT011'")
		execute("update organizations set name = 'Yale-New Haven Hospital Saint Raphael Campus' where nci_institute_code = 'CT023'")
		execute("update organizations set name = 'Stamford Hospital/Bennett Cancer Center' where nci_institute_code = 'CT033'")
		execute("update organizations set name = 'Johnson Memorial Cancer Center' where nci_institute_code = 'CT040'")
		execute("update organizations set name = 'Smilow Cancer Hospital-Torrington Care Center' where nci_institute_code = 'CT043'")
		execute("update organizations set name = 'Veterans Affairs Connecticut Healthcare System-West Haven Campus' where nci_institute_code = 'CT063'")
		execute("update organizations set name = 'Windham Hospital' where nci_institute_code = 'CT070'")
		execute("update organizations set name = 'Smilow Cancer Hospital-Hamden Care Center' where nci_institute_code = 'CT077'")
		execute("update organizations set name = 'Yale-New Haven Shoreline Medical Center' where nci_institute_code = 'CT078'")
		execute("update organizations set name = 'Smilow Cancer Hospital-Waterbury Care Center' where nci_institute_code = 'CT079'")
		execute("update organizations set name = 'Medical Oncology and Blood Disorders LLP-Hartford' where nci_institute_code = 'CT087'")
		execute("update organizations set name = 'Medical Oncology and Blood Disorders LLP-Manchester' where nci_institute_code = 'CT093'")
		execute("update organizations set name = 'Medical Oncology and Blood Disorders LLP-Vernon' where nci_institute_code = 'CT101'")
		execute("update organizations set name = 'Smilow Cancer Hospital-Orange Care Center' where nci_institute_code = 'CT113'")
		execute("update organizations set name = 'Smilow Cancer Hospital-Derby Care Center' where nci_institute_code = 'CT114'")
		execute("update organizations set name = 'MedStar Georgetown University Hospital' where nci_institute_code = 'DC005'")
	}
	
	void m7(){
		execute("update organizations set name = 'MedStar Washington Hospital Center' where nci_institute_code = 'DC007'")
		execute("update organizations set name = 'Christiana Care Health System-Christiana Hospital' where nci_institute_code = 'DE002'")
		execute("update organizations set name = 'Halifax Health Medical Center-Centers for Oncology' where nci_institute_code = 'FL001'")
		execute("update organizations set name = 'Memorial Regional Hospital/Joe DiMaggio Children\\'s Hospital' where nci_institute_code = 'FL023'")
		execute("update organizations set name = 'University of Miami Hospital-Cedars Medical Center' where nci_institute_code = 'FL035'")
		execute("update organizations set name = 'Broward Health Medical Center' where nci_institute_code = 'FL045'")
		execute("update organizations set name = 'Boca Raton Regional Hospital' where nci_institute_code = 'FL050'")
		execute("update organizations set name = 'Morton Plant Mease' where nci_institute_code = 'FL053'")
		execute("update organizations set name = 'Mayo Clinic in Florida' where nci_institute_code = 'FL080'")
		execute("update organizations set name = 'Florida Cancer Institute-New Port Richey' where nci_institute_code = 'FL100'")
		execute("update organizations set name = 'Florida Cancer Specialists-Cornerstone Cancer Center' where nci_institute_code = 'FL110'")
		execute("update organizations set name = 'Florida Cancer Specialists-North Habana' where nci_institute_code = 'FL116'")
		execute("update organizations set name = 'Florida Hospital Cancer Institute at Winter Park' where nci_institute_code = 'FL135'")
		execute("update organizations set name = 'Florida Cancer Specialists-Lecanto' where nci_institute_code = 'FL136'")
		execute("update organizations set name = 'Nemours Children\\'s Clinic - Fort Myers' where nci_institute_code = 'FL192'")
		execute("update organizations set name = 'Cancer Care Centers of Brevard-Rockledge' where nci_institute_code = 'FL197'")
		execute("update organizations set name = 'South Florida Oncology-Hematology' where nci_institute_code = 'FL202'")
		execute("update organizations set name = 'Golisano Children\\'s Hospital of Southwest Florida' where nci_institute_code = 'FL203'")
		execute("update organizations set name = 'Integrated Community Oncology Network-Orange Park Cancer Center' where nci_institute_code = 'FL206'")
		execute("update organizations set name = 'Indian River Medical Center' where nci_institute_code = 'FL213'")
		execute("update organizations set name = 'Integrated Community Oncology Network-Southside Cancer Center' where nci_institute_code = 'FL220'")
		execute("update organizations set name = 'Martin Hospital South' where nci_institute_code = 'FL224'")
		execute("update organizations set name = 'Martin Medical Center' where nci_institute_code = 'FL231'")
		execute("update organizations set name = 'Robert and Carol Weissman Cancer Center at Martin Health' where nci_institute_code = 'FL236'")
		execute("update organizations set name = 'Women\\'s Cancer Associates' where nci_institute_code = 'FL249'")
	}
	
	void m8(){	
		execute("update organizations set name = '21st Century Oncology-Port Charlotte' where nci_institute_code = 'FL252'")
		execute("update organizations set name = 'Cancer Specialists of North Florida-Saint Vincent\\'s' where nci_institute_code = 'FL263'")
		execute("update organizations set name = 'Integrated Community Oncology Network-Cancer Center of Putnam' where nci_institute_code = 'FL271'")
		execute("update organizations set name = 'Broward Health North' where nci_institute_code = 'FL272'")
		execute("update organizations set name = 'Florida Cancer Specialists-Armenia' where nci_institute_code = 'FL274'")
		execute("update organizations set name = 'Premier Hematology and Oncology' where nci_institute_code = 'FL277'")
		execute("update organizations set name = 'Florida Cancer Specialists-West Palm Beach' where nci_institute_code = 'FL288'")
		execute("update organizations set name = 'Palms West Hospital' where nci_institute_code = 'FL304'")
		execute("update organizations set name = 'Cleveland Clinic-Weston' where nci_institute_code = 'FL310'")
		execute("update organizations set name = 'Woodlands Medical Specialists (Hope Medical Group)' where nci_institute_code = 'FL311'")
		execute("update organizations set name = 'Florida Hospital Cancer Institute-Altamonte' where nci_institute_code = 'FL312'")
		execute("update organizations set name = 'Cancer Institute of Florida' where nci_institute_code = 'FL316'")
		execute("update organizations set name = 'Broward Health Imperial Point' where nci_institute_code = 'FL319'")
		execute("update organizations set name = 'Cancer Specialists of North Florida' where nci_institute_code = 'FL335'")
		execute("update organizations set name = 'Integrated Community Oncology Network-Flager Cancer Center' where nci_institute_code = 'FL336'")
		execute("update organizations set name = 'Integrated Community Oncology Network-Baptist Medical Center South' where nci_institute_code = 'FL341'")
		execute("update organizations set name = 'Florida Cancer Specialists-Clearwater/Morton' where nci_institute_code = 'FL347'")
		execute("update organizations set name = 'Florida Cancer Specialists-Tavares' where nci_institute_code = 'FL353'")
		execute("update organizations set name = '21st Century Oncology-Lehigh Acres' where nci_institute_code = 'FL360'")
		execute("update organizations set name = 'Integrated Community Oncology Network-Florida Cancer Center Beaches' where nci_institute_code = 'FL367'")
		execute("update organizations set name = 'Tallahassee Memorial Surgical Specialists' where nci_institute_code = 'FL369'")
		execute("update organizations set name = '21st Century Oncology-Fort Myers' where nci_institute_code = 'FL384'")
		execute("update organizations set name = 'Florida Cancer Specialists-Tampa' where nci_institute_code = 'FL388'")
		execute("update organizations set name = 'Moffitt Cancer Center at Tampa General Hospital' where nci_institute_code = 'FL395'")
		execute("update organizations set name = 'Longevity Medical PLC' where nci_institute_code = 'FL403'")
	}
	
	void m9(){
		execute("update organizations set name = 'South Florida Radiation Oncology-Boynton Beach' where nci_institute_code = 'FL421'")
		execute("update organizations set name = 'Emory University Hospital Midtown' where nci_institute_code = 'GA013'")
		execute("update organizations set name = 'Georgia Regents University' where nci_institute_code = 'GA020'")
		execute("update organizations set name = 'Memorial University Medical Center' where nci_institute_code = 'GA022'")
		execute("update organizations set name = 'Children\\'s Healthcare of Atlanta - Scottish Rite' where nci_institute_code = 'GA026'")
		execute("update organizations set name = 'John B Amos Cancer Center' where nci_institute_code = 'GA045'")
		execute("update organizations set name = 'South Georgia Medical Center/Pearlman Cancer Center' where nci_institute_code = 'GA069'")
		execute("update organizations set name = 'Cobb Hospital and Medical Center' where nci_institute_code = 'GA076'")
		execute("update organizations set name = 'Augusta Oncology Associates PC-Wheeler' where nci_institute_code = 'GA078'")
		execute("update organizations set name = 'Augusta Oncology Associates PC-Saint Sebastian' where nci_institute_code = 'GA105'")
		execute("update organizations set name = 'Lewis Cancer and Research Pavilion at Saint Joseph\\'s/Candler' where nci_institute_code = 'GA106'")
		execute("update organizations set name = 'Georgia Gynecology Oncology' where nci_institute_code = 'GA120'")
		execute("update organizations set name = 'Saint Francis Hospital Columbus' where nci_institute_code = 'GA150'")
		execute("update organizations set name = 'Harbin Clinic Medical Oncology and Clinical Research' where nci_institute_code = 'GA198'")
		execute("update organizations set name = 'The Cancer Center of Hawaii-Liliha' where nci_institute_code = 'HI008'")
		execute("update organizations set name = 'Wilcox Memorial Hospital and Kauai Medical Clinic' where nci_institute_code = 'HI014'")
		execute("update organizations set name = 'Pali Momi Medical Center' where nci_institute_code = 'HI017'")
		execute("update organizations set name = 'Oncare Hawaii Inc-Pali Momi' where nci_institute_code = 'HI027'")
		execute("update organizations set name = 'The Cancer Center of Hawaii-Leeward' where nci_institute_code = 'HI030'")
		execute("update organizations set name = 'Hepatic Tumor Study Group' where nci_institute_code = 'HTSG'")
		execute("update organizations set name = 'Blank Children\\'s Hospital' where nci_institute_code = 'IA005'")
		execute("update organizations set name = 'Oncology Associates at Mercy Medical Center' where nci_institute_code = 'IA024'")
		execute("update organizations set name = 'Burgess Health Center' where nci_institute_code = 'IA031'")
		execute("update organizations set name = 'Siouxland Hematology Oncology Associates LLP' where nci_institute_code = 'IA034'")
		execute("update organizations set name = 'Great River Medical Center' where nci_institute_code = 'IA060'")
	}
	
	void m10(){
		execute("update organizations set name = 'Iowa Cancer Specialists-Genesis Cancer Center' where nci_institute_code = 'IA061'")
		execute("update organizations set name = 'Physicians\\' Clinic of Iowa PC' where nci_institute_code = 'IA066'")
		execute("update organizations set name = 'Saint Alphonsus Health System-Nampa' where nci_institute_code = 'ID009'")
		execute("update organizations set name = 'Saint Luke\\'s Mountain States Tumor Institute-Twin Falls' where nci_institute_code = 'ID023'")
		execute("update organizations set name = 'Rosalind Franklin University-Chicago Medical School' where nci_institute_code = 'IL009'")
		execute("update organizations set name = 'Advocate Sherman Hospital' where nci_institute_code = 'IL015'")
		execute("update organizations set name = 'Evanston CCOP-NorthShore University HealthSystem' where nci_institute_code = 'IL018'")
		execute("update organizations set name = 'Vanguard West Suburban Medical Center' where nci_institute_code = 'IL020'")
		execute("update organizations set name = 'Illinois Cancer Specialists-Hinsdale' where nci_institute_code = 'IL032'")
		execute("update organizations set name = 'Ann and Robert H Lurie Children\\'s Hospital of Chicago' where nci_institute_code = 'IL045'")
		execute("update organizations set name = 'Presence Resurrection Medical Center' where nci_institute_code = 'IL056'")
		execute("update organizations set name = 'Presence Saint Joseph Hospital-Chicago' where nci_institute_code = 'IL065'")
		execute("update organizations set name = 'Presence Saint Mary\\'s Hospital' where nci_institute_code = 'IL069'")
		execute("update organizations set name = 'OSF Saint Anthony Medical Center' where nci_institute_code = 'IL073'")
		execute("update organizations set name = 'Carle Clinic-Urbana Main' where nci_institute_code = 'IL086'")
		execute("update organizations set name = 'Southern Illinois University School of Medicine' where nci_institute_code = 'IL096'")
		execute("update organizations set name = 'Edward Hospital/Cancer Center' where nci_institute_code = 'IL104'")
		execute("update organizations set name = 'Franciscan St. James Health-Chicago Heights Campus' where nci_institute_code = 'IL112'")
		execute("update organizations set name = 'Western Illinois Cancer Treatment Center' where nci_institute_code = 'IL140'")
		execute("update organizations set name = 'NorthShore Medical Center' where nci_institute_code = 'IL154'")
		execute("update organizations set name = 'Valley Radiation Oncology' where nci_institute_code = 'IL162'")
		execute("update organizations set name = 'Carle Cancer Center' where nci_institute_code = 'IL168'")
		execute("update organizations set name = 'Adventist La Grange Memorial Hospital' where nci_institute_code = 'IL171'")
		execute("update organizations set name = 'Illinois Cancer Specialists-Niles' where nci_institute_code = 'IL176'")
		execute("update organizations set name = 'Mid-Illinois Hematology Oncology Associates Limited' where nci_institute_code = 'IL181'")
	}
	
		void m11(){
		execute("update organizations set name = 'Cancer Care Specialists of Central Illinois' where nci_institute_code = 'IL185'")
		execute("update organizations set name = 'Illinois CancerCare Galesburg' where nci_institute_code = 'IL188'")
		execute("update organizations set name = 'Advocate Hope Children\\'s Hospital' where nci_institute_code = 'IL202'")
		execute("update organizations set name = 'Freeport Memorial Hospital/Leonard C Ferguson Cancer Center' where nci_institute_code = 'IL203'")
		execute("update organizations set name = 'Edward H Kaplan MD and Associates' where nci_institute_code = 'IL219'")
		execute("update organizations set name = 'NorthShore Hematology Oncology-Libertyville' where nci_institute_code = 'IL224'")
		execute("update organizations set name = 'Community Cancer Center Foundation' where nci_institute_code = 'IL232'")
		execute("update organizations set name = 'SwedishAmerican Regional Cancer Center/ACT' where nci_institute_code = 'IL249'")
		execute("update organizations set name = 'Illinois CancerCare-Galesburg Cottage Plaza Office' where nci_institute_code = 'IL273'")
		execute("update organizations set name = 'Franciscan St. James Health-Olympia Fields Campus' where nci_institute_code = 'IL278'")
		execute("update organizations set name = 'Alexian Brothers Medical and Cancer Center' where nci_institute_code = 'IL280'")
		execute("update organizations set name = 'Sudarshan K Sharma MD Limted-Gynecologic Oncology' where nci_institute_code = 'IL305'")
		execute("update organizations set name = 'Stoffel, Thomas J MD (UIA Investigator)' where nci_institute_code = 'IL313'")
		execute("update organizations set name = 'Presence Saint Mary\\'s Cancer Center' where nci_institute_code = 'IL318'")
		execute("update organizations set name = 'Radiation Oncology of Northern Illinois' where nci_institute_code = 'IL371'")
		execute("update organizations set name = 'UIC Cancer Center at MacNeal Hospital' where nci_institute_code = 'IL372'")
		execute("update organizations set name = 'Franciscan St. Francis Health-Beech Grove' where nci_institute_code = 'IN002'")
		execute("update organizations set name = 'Indiana University Hospital/Melvin and Bren Simon Cancer Center' where nci_institute_code = 'IN007'")
		execute("update organizations set name = 'Saint Joseph Regional Medical Center-Mishawaka' where nci_institute_code = 'IN015'")
		execute("update organizations set name = 'Parkview Hospital' where nci_institute_code = 'IN017'")
		execute("update organizations set name = 'IU Health Ball Memorial Hospital' where nci_institute_code = 'IN022'")
		execute("update organizations set name = 'Indiana University Health La Porte Hospital' where nci_institute_code = 'IN035'")
		execute("update organizations set name = 'IU Health Methodist Hospital' where nci_institute_code = 'IN046'")
		execute("update organizations set name = 'Michiana Hematology Oncology PC-South Bend' where nci_institute_code = 'IN051'")
		execute("update organizations set name = 'Cancer Health Treatment Centers PC-Crown Point' where nci_institute_code = 'IN052'")
	}
	
	void m12(){
		execute("update organizations set name = 'Michiana Hematology Oncology PC-Mishawaka' where nci_institute_code = 'IN054'")
		execute("update organizations set name = 'Community Howard Regional Health' where nci_institute_code = 'IN062'")
		execute("update organizations set name = 'Saint Vincent Anderson Regional Hospital/Cancer Center' where nci_institute_code = 'IN064'")
		execute("update organizations set name = 'Health and Oncology Services Inc' where nci_institute_code = 'IN065'")
		execute("update organizations set name = 'Floyd Memorial Cancer Center of Indiana' where nci_institute_code = 'IN066'")
		execute("update organizations set name = 'IU Health Arnett Cancer Care' where nci_institute_code = 'IN073'")
		execute("update organizations set name = 'Oncology Hematology Associates of Southwest Indiana' where nci_institute_code = 'IN076'")
		execute("update organizations set name = 'Indiana University Health Goshen Center for Cancer Care' where nci_institute_code = 'IN083'")
		execute("update organizations set name = 'Indiana University Health Bloomington' where nci_institute_code = 'IN085'")
		execute("update organizations set name = 'Franciscan St. Francis Health' where nci_institute_code = 'IN087'")
		execute("update organizations set name = 'IU Health Central Indiana Cancer Centers-South' where nci_institute_code = 'IN092'")
		execute("update organizations set name = 'IU Health Central Indiana Cancer Centers-Fishers' where nci_institute_code = 'IN105'")
		execute("update organizations set name = 'Michiana Hematology Oncology PC-Elkhart' where nci_institute_code = 'IN108'")
		execute("update organizations set name = 'Franciscan Saint Margaret Health-Hammond Campus' where nci_institute_code = 'IN120'")
		execute("update organizations set name = 'Horizon Oncology Research Inc' where nci_institute_code = 'IN124'")
		execute("update organizations set name = 'Community Breast Care South' where nci_institute_code = 'IN127'")
		execute("update organizations set name = 'Allied Physicians of Michiana' where nci_institute_code = 'IN132'")
		execute("update organizations set name = 'IU Health North Hospital' where nci_institute_code = 'IN135'")
		execute("update organizations set name = 'IU Health West' where nci_institute_code = 'IN140'")
		execute("update organizations set name = 'Franciscan St. Francis Health-Indianapolis' where nci_institute_code = 'IN142'")
		execute("update organizations set name = 'Franciscan Physician Network-Kendrick Colon and Rectal Surgeons' where nci_institute_code = 'IN148'")
		execute("update organizations set name = 'Community Hospital East' where nci_institute_code = 'IN156'")
		execute("update organizations set name = 'Franciscan Saint Margaret Health-Dyer Campus' where nci_institute_code = 'IN158'")
		execute("update organizations set name = 'Franciscan Saint Francis Health-Mooresville' where nci_institute_code = 'IN162'")
		execute("update organizations set name = 'Via Christi Hospital-Pittsburg' where nci_institute_code = 'KS023'")
	}
	
	void m13(){
		execute("update organizations set name = 'Hutchinson Regional Medical Center' where nci_institute_code = 'KS026'")
		execute("update organizations set name = 'Salina Regional Health Center' where nci_institute_code = 'KS029'")
		execute("update organizations set name = 'Shawnee Mission Medical Center-KCCC' where nci_institute_code = 'KS043'")
		execute("update organizations set name = 'Cancer Center of Kansas-Wichita Medical Arts Tower' where nci_institute_code = 'KS067'")
		execute("update organizations set name = 'The James Graham Brown Cancer Center at University of Louisville' where nci_institute_code = 'KY002'")
		execute("update organizations set name = 'Saint Elizabeth Fort Thomas' where nci_institute_code = 'KY016'")
		execute("update organizations set name = 'The Medical Center-Bowling Green' where nci_institute_code = 'KY019'")
		execute("update organizations set name = 'Baptist Health Louisville' where nci_institute_code = 'KY024'")
		execute("update organizations set name = 'Baptist Health Lexington' where nci_institute_code = 'KY026'")
		execute("update organizations set name = 'Owensboro Health Mitchell Memorial Cancer Center' where nci_institute_code = 'KY051'")
		execute("update organizations set name = 'Oncology Associates of West Kentucky' where nci_institute_code = 'KY062'")
		execute("update organizations set name = 'Louisville Thoracic Specialists' where nci_institute_code = 'KY066'")
		execute("update organizations set name = 'Baptist Health Corbin' where nci_institute_code = 'KY072'")
		execute("update organizations set name = 'Saint Joseph Radiation Oncology Resource Center' where nci_institute_code = 'KY079'")
		execute("update organizations set name = 'Cancer and Blood Specialists-Bluegrass' where nci_institute_code = 'KY084'")
		execute("update organizations set name = 'Children\\'s Hospital-Main Campus' where nci_institute_code = 'LA004'")
		execute("update organizations set name = 'Louisiana State University Health Sciences Center Shreveport' where nci_institute_code = 'LA017'")
		execute("update organizations set name = 'Terrebonne Medical Center-Mary Bird Perkins Cancer Center' where nci_institute_code = 'LA028'")
		execute("update organizations set name = 'Interim LSU Public Hospital' where nci_institute_code = 'LA029'")
		execute("update organizations set name = 'Ochsner Baptist Medical Center' where nci_institute_code = 'LA032'")
		execute("update organizations set name = 'Willis-Knighton Medical and Cancer Center' where nci_institute_code = 'LA034'")
		execute("update organizations set name = 'Hematology/Oncology Clinic LLP' where nci_institute_code = 'LA062'")
		execute("update organizations set name = 'West Jefferson Medical Center' where nci_institute_code = 'LA073'")
		execute("update organizations set name = 'Metairie Oncologists LLC' where nci_institute_code = 'LA102'")
		execute("update organizations set name = 'Holyoke Medical Center' where nci_institute_code = 'MA001'")
	}
	
	void m14(){	
		execute("update organizations set name = 'University of Massachusetts Memorial Health Care' where nci_institute_code = 'MA009'")
		execute("update organizations set name = 'Lahey Hospital and Medical Center' where nci_institute_code = 'MA017'")
		execute("update organizations set name = 'Children\\'s Hospital Boston' where nci_institute_code = 'MA042'")
		execute("update organizations set name = 'Brigham and Women\\'s Faulkner Hospital' where nci_institute_code = 'MA046'")
		execute("update organizations set name = 'Floating Hospital for Children at Tufts Medical Center' where nci_institute_code = 'MA080'")
		execute("update organizations set name = 'Mass General/North Shore Cancer Center' where nci_institute_code = 'MA093'")
		execute("update organizations set name = 'MetroWest Medical Center-Framingham Union Hospital' where nci_institute_code = 'MA094'")
		execute("update organizations set name = 'Saint Vincent Hospital/Reliant Medical Group' where nci_institute_code = 'MA098'")
		execute("update organizations set name = 'Emerson Hospital/MGH Cancer Center' where nci_institute_code = 'MA100'")
		execute("update organizations set name = 'MetroWest Medical Center-Leonard Morse Hospital' where nci_institute_code = 'MA111'")
		execute("update organizations set name = 'Southcoast Hospital Group-Southcoast Centers for Cancer Care' where nci_institute_code = 'MA112'")
		execute("update organizations set name = 'Norwood Hospital' where nci_institute_code = 'MA123'")
		execute("update organizations set name = 'Walter Reed National Military Medical Center' where nci_institute_code = 'MD001'")
		execute("update organizations set name = 'MedStar Montgomery Medical Center' where nci_institute_code = 'MD008'")
		execute("update organizations set name = 'University of Maryland Saint Joseph Medical Center' where nci_institute_code = 'MD019'")
		execute("update organizations set name = 'MedStar Union Memorial Hospital' where nci_institute_code = 'MD023'")
		execute("update organizations set name = 'MedStar Franklin Square Medical Center/Weinberg Cancer Institute' where nci_institute_code = 'MD029'")
		execute("update organizations set name = 'MedStar Good Samaritan' where nci_institute_code = 'MD030'")
		execute("update organizations set name = 'Western Maryland Health System' where nci_institute_code = 'MD031'")
		execute("update organizations set name = 'MedStar Harbor Hospital' where nci_institute_code = 'MD039'")
		execute("update organizations set name = 'Meritus Medical Center' where nci_institute_code = 'MD048'")
		execute("update organizations set name = 'AAMC Oncology and Hematology' where nci_institute_code = 'MD049'")
		execute("update organizations set name = 'MedStar Saint Mary\\'s Hospital' where nci_institute_code = 'MD073'")
		execute("update organizations set name = 'Mark O Hatfield-Warren Grant Magnuson Clinical Center' where nci_institute_code = 'MD115'")
		execute("update organizations set name = 'Signature Breast Care' where nci_institute_code = 'MD165'")
	}
	
	void m15(){
		execute("update organizations set name = 'Maryland Oncology Hematology PA-Silver Spring' where nci_institute_code = 'MD170'")
		execute("update organizations set name = '21st Century Oncology-Berlin' where nci_institute_code = 'MD171'")
		execute("update organizations set name = 'Maine Children\\'s Cancer Program' where nci_institute_code = 'ME002'")
		execute("update organizations set name = 'Maine General Medical Center-Thayer' where nci_institute_code = 'ME008'")
		execute("update organizations set name = 'Maine Medical Center-Bramhall Campus' where nci_institute_code = 'ME010'")
		execute("update organizations set name = 'Maine Medical Center- Scarborough Campus' where nci_institute_code = 'ME018'")
		execute("update organizations set name = 'Maine Center for Cancer Medicine Blood Disorders-Brunswick' where nci_institute_code = 'ME021'")
		execute("update organizations set name = 'Maine Center for Cancer Medicine and Blood Disorders-Scarborough' where nci_institute_code = 'ME023'")
		execute("update organizations set name = 'Maine Center for Cancer Medicine-Biddeford' where nci_institute_code = 'ME031'")
		execute("update organizations set name = 'Maine Medical Partners Women\\'s Health and Gynecologic Oncology' where nci_institute_code = 'ME033'")
		execute("update organizations set name = 'Maine Center for Cancer Medicine and Blood Disorders-Sanford' where nci_institute_code = 'ME035'")
		execute("update organizations set name = 'William Beaumont Hospital-Royal Oak' where nci_institute_code = 'MI005'")
		execute("update organizations set name = 'University of Michigan Health System-Cancer Center' where nci_institute_code = 'MI014'")
		execute("update organizations set name = 'Oakwood Healthcare Inc' where nci_institute_code = 'MI015'")
		execute("update organizations set name = 'Michigan State University Clinical Center' where nci_institute_code = 'MI038'")
		execute("update organizations set name = 'Bronson Battle Creek' where nci_institute_code = 'MI045'")
		execute("update organizations set name = 'Botsford Hospital' where nci_institute_code = 'MI054'")
		execute("update organizations set name = 'Henry Ford Macomb Hospital-Warren' where nci_institute_code = 'MI055'")
		execute("update organizations set name = 'Saint Joseph Mercy Port Huron' where nci_institute_code = 'MI057'")
		execute("update organizations set name = 'Mercy Health Partners-Hackley Campus' where nci_institute_code = 'MI075'")
		execute("update organizations set name = 'William Beaumont Hospital-Grosse Point' where nci_institute_code = 'MI077'")
		execute("update organizations set name = 'Allegiance Health' where nci_institute_code = 'MI079'")
		execute("update organizations set name = 'McLaren Northern Michigan' where nci_institute_code = 'MI081'")
		execute("update organizations set name = 'Covenant Medical Center Cooper' where nci_institute_code = 'MI084'")
		execute("update organizations set name = 'Genesys Regional Medical Center-West Flint Campus' where nci_institute_code = 'MI088'")
	}
	
	void m16(){
		execute("update organizations set name = 'Covenant Medical Center Harrison' where nci_institute_code = 'MI120'")
		execute("update organizations set name = 'Spectrum Health at Butterworth Campus' where nci_institute_code = 'MI132'")
		execute("update organizations set name = 'Henry Ford Macomb Hospital' where nci_institute_code = 'MI137'")
		execute("update organizations set name = 'McLaren-Bay Regional West Campus' where nci_institute_code = 'MI148'")
		execute("update organizations set name = 'Spectrum Health Medical Group' where nci_institute_code = 'MI167'")
		execute("update organizations set name = 'McLaren Cancer Institute' where nci_institute_code = 'MI169'")
		execute("update organizations set name = 'Toledo Clinic Cancer Centers-Adrian' where nci_institute_code = 'MI187'")
		execute("update organizations set name = 'Toledo Clinic Cancer Centers-Monroe' where nci_institute_code = 'MI188'")
		execute("update organizations set name = 'Marquette General Hematology Oncology' where nci_institute_code = 'MI226'")
		execute("update organizations set name = 'Northern Oncology Services PLLC' where nci_institute_code = 'MI235'")
		execute("update organizations set name = 'Oakwood Center for Hematology and Oncology-Downriver' where nci_institute_code = 'MI241'")
		execute("update organizations set name = 'Lake Orion-Rochester Oncology' where nci_institute_code = 'MI245'")
		execute("update organizations set name = 'Marie Yeager Cancer Center' where nci_institute_code = 'MI246'")
		execute("update organizations set name = 'McLaren Cancer Institute-Lapeer Campus' where nci_institute_code = 'MI263'")
		execute("update organizations set name = 'Mercy Health Partners-Mercy Campus' where nci_institute_code = 'MI269'")
		execute("update organizations set name = 'Essentia Health Saint Joseph\\'s Medical Center' where nci_institute_code = 'MN012'")
		execute("update organizations set name = 'Essentia Health Saint Mary\\'s Medical Center' where nci_institute_code = 'MN023'")
		execute("update organizations set name = 'Essentia Health Duluth Clinic CCOP' where nci_institute_code = 'MN024'")
		execute("update organizations set name = 'Mayo Clinic' where nci_institute_code = 'MN026'")
		execute("update organizations set name = 'Coborn Cancer Center at Saint Cloud Hospital' where nci_institute_code = 'MN040'")
		execute("update organizations set name = 'Mayo Clinic Health System in Red Wing' where nci_institute_code = 'MN053'")
		execute("update organizations set name = 'Lake Region Healthcare Corporation-Cancer Care' where nci_institute_code = 'MN058'")
		execute("update organizations set name = 'Sanford Clinic Perham' where nci_institute_code = 'MN067'")
		execute("update organizations set name = 'Mayo Clinic Health Systems-Mankato' where nci_institute_code = 'MN079'")
		execute("update organizations set name = 'Mayo Clinic Health System in Albert Lea' where nci_institute_code = 'MN086'")
	}
	
	void m17(){
		execute("update organizations set name = 'Sanford Clinic North-Bemidji' where nci_institute_code = 'MN089'")
		execute("update organizations set name = 'Mercy Hospital Saint Louis' where nci_institute_code = 'MO021'")
		execute("update organizations set name = 'Children\\'s Mercy Hospitals and Clinics' where nci_institute_code = 'MO024'")
		execute("update organizations set name = 'Mercy Hospital-Joplin' where nci_institute_code = 'MO034'")
		execute("update organizations set name = 'MUHC-Women\\'s and Children\\'s Hospital' where nci_institute_code = 'MO038'")
		execute("update organizations set name = 'Mercy-Springfield' where nci_institute_code = 'MO043'")
		execute("update organizations set name = 'Saint Louis Cancer and Breast Institute-South City' where nci_institute_code = 'MO051'")
		execute("update organizations set name = 'Veterans Administration/Harry S Truman Memorial Hospital' where nci_institute_code = 'MO069'")
		execute("update organizations set name = 'Mercy Clinic Cancer and Hematology/Chub O\\'Reilly Cancer Center' where nci_institute_code = 'MO076'")
		execute("update organizations set name = 'Missouri Cancer Care PC-Wentzville' where nci_institute_code = 'MO090'")
		execute("update organizations set name = 'Centerpoint Medical Center LLC' where nci_institute_code = 'MO092'")
		execute("update organizations set name = 'Siteman Cancer Center at Washington University' where nci_institute_code = 'MO111'")
		execute("update organizations set name = 'Cape Radiation Oncology' where nci_institute_code = 'MO133'")
		execute("update organizations set name = 'Capital Region Medical Center-Goldschmidt Cancer Center' where nci_institute_code = 'MO142'")
		execute("update organizations set name = 'Carter and Chosney MD PC' where nci_institute_code = 'MO160'")
		execute("update organizations set name = 'Hematology Oncology at BridgePoint' where nci_institute_code = 'MS003'")
		execute("update organizations set name = 'Forrest General Hospital' where nci_institute_code = 'MS008'")
		execute("update organizations set name = 'Singing River Hospital' where nci_institute_code = 'MS012'")
		execute("update organizations set name = 'Mississippi Oncology Associates' where nci_institute_code = 'MS047'")
		execute("update organizations set name = 'Hi-Line Sletten Cancer Center' where nci_institute_code = 'MT017'")
		execute("update organizations set name = 'Billings Clinic Hospital' where nci_institute_code = 'MT024'")
		execute("update organizations set name = 'Frontier Cancer Center and Blood Institutes-Billings' where nci_institute_code = 'MT027'")
		execute("update organizations set name = 'Cone Health Cancer Center' where nci_institute_code = 'NC004'")
		execute("update organizations set name = 'University of North Carolina at Chapel Hill' where nci_institute_code = 'NC007'")
		execute("update organizations set name = 'Wake Medical Center-Breast Screening and Diagnostic' where nci_institute_code = 'NC008'")
	}
	
	void m18(){	
		execute("update organizations set name = 'East Carolina University' where nci_institute_code = 'NC012'")
		execute("update organizations set name = 'Vidant Medical Center' where nci_institute_code = 'NC013'")
		execute("update organizations set name = 'CarolinaEast Health System-Medical Center' where nci_institute_code = 'NC026'")
		execute("update organizations set name = 'Catawba Valley Medical Center' where nci_institute_code = 'NC027'")
		execute("update organizations set name = 'Carolinas Medical Center/Levine Cancer Institute' where nci_institute_code = 'NC042'")
		execute("update organizations set name = 'New Hanover Regional Medical Center/Zimmer Cancer Center' where nci_institute_code = 'NC043'")
		execute("update organizations set name = 'Asheville Hematology-Oncology Associates' where nci_institute_code = 'NC058'")
		execute("update organizations set name = 'Levine Cancer Institute-SouthPark/Morrocroft' where nci_institute_code = 'NC059'")
		execute("update organizations set name = 'CaroMont Regional Medical Center' where nci_institute_code = 'NC069'")
		execute("update organizations set name = 'Cape Fear Cancer Specialists' where nci_institute_code = 'NC077'")
		execute("update organizations set name = 'FirstHealth of the Carolinas-Moore Regional Hospital' where nci_institute_code = 'NC081'")
		execute("update organizations set name = 'Levine Cancer Institute-Billingsley' where nci_institute_code = 'NC085'")
		execute("update organizations set name = 'Hope Women\\'s Cancer Centers-Ashville' where nci_institute_code = 'NC096'")
		execute("update organizations set name = 'Hendersonville Hematology and Oncology at Pardee' where nci_institute_code = 'NC104'")
		execute("update organizations set name = 'Virginia Oncology Associates-Elizabeth City' where nci_institute_code = 'NC125'")
		execute("update organizations set name = 'Carolinas Medical Center-Union' where nci_institute_code = 'NC132'")
		execute("update organizations set name = 'Surgical Specialists of Charlotte PA' where nci_institute_code = 'NC142'")
		execute("update organizations set name = 'Outer Banks Hospital' where nci_institute_code = 'NC155'")
		execute("update organizations set name = 'Cornerstone Hematology and Oncology' where nci_institute_code = 'NC157'")
		execute("update organizations set name = 'Levine Cancer Institute-Charlotte' where nci_institute_code = 'NC158'")
		execute("update organizations set name = 'Coastal Carolina Radiation Oncology' where nci_institute_code = 'NC164'")
		execute("update organizations set name = 'Stanly Regional Medical Center' where nci_institute_code = 'NC165'")
		execute("update organizations set name = 'Duke Health Center at North Duke Street' where nci_institute_code = 'NC166'")
		execute("update organizations set name = 'Park Ridge Health' where nci_institute_code = 'NC191'")
		execute("update organizations set name = 'Levine Cancer Institute-Pineville' where nci_institute_code = 'NC193'")
	}
	
	void m19(){
		execute("update organizations set name = 'Columbus Regional Healthcare System/Donayre Cancer Care Center' where nci_institute_code = 'NC203'")
		execute("update organizations set name = 'Levine Cancer Institute-Cornelius' where nci_institute_code = 'NC205'")
		execute("update organizations set name = 'NCI Division of Cancer Biology' where nci_institute_code = 'NCICBD'")
		execute("update organizations set name = 'Developmental Therapeutics Program' where nci_institute_code = 'NCIDTP'")
		execute("update organizations set name = 'NCI Division of Cancer Epidemiology and Genetics' where nci_institute_code = 'NCIEPI'")
		execute("update organizations set name = 'Sanford Medical Center-Fargo' where nci_institute_code = 'ND003'")
		execute("update organizations set name = 'Sanford Roger Maris Cancer Center' where nci_institute_code = 'ND005'")
		execute("update organizations set name = 'Sanford Bismarck Medical Center' where nci_institute_code = 'ND007'")
		execute("update organizations set name = 'Essentia Health Cancer Center-South University Clinic' where nci_institute_code = 'ND009'")
		execute("update organizations set name = 'Sanford Clinic Valley City' where nci_institute_code = 'ND018'")
		execute("update organizations set name = 'Sanford Clinic North-Fargo' where nci_institute_code = 'ND031'")
		execute("update organizations set name = 'Children\\'s Hospital and Medical Center of Omaha' where nci_institute_code = 'NE006'")
		execute("update organizations set name = 'Nebraska Methodist Hospital' where nci_institute_code = 'NE007'")
		execute("update organizations set name = 'Good Samaritan Hospital' where nci_institute_code = 'NE011'")
		execute("update organizations set name = 'Nebraska Cancer Research Center' where nci_institute_code = 'NE037'")
		execute("update organizations set name = 'Lahey Clinic Nashua' where nci_institute_code = 'NH027'")
		execute("update organizations set name = 'LRGHealthcare-Lakes Region General Hospital' where nci_institute_code = 'NH029'")
		execute("update organizations set name = 'Parkland Medical Center' where nci_institute_code = 'NH031'")
		execute("update organizations set name = 'Norris Cotton Cancer Center-Manchester' where nci_institute_code = 'NH039'")
		execute("update organizations set name = 'National Institute of Allergy and Infectious Disease' where nci_institute_code = 'NIAID'")
		execute("update organizations set name = 'Veterans Administration New Jersey Health Care System' where nci_institute_code = 'NJ001'")
		execute("update organizations set name = 'Overlook Medical Center' where nci_institute_code = 'NJ026'")
		execute("update organizations set name = 'Morristown Medical Center' where nci_institute_code = 'NJ028'")
		execute("update organizations set name = 'Inspira Medical Center Vineland' where nci_institute_code = 'NJ031'")
		execute("update organizations set name = 'University Medical Center of Princeton at Plainsboro' where nci_institute_code = 'NJ039'")
	}
		
	void m20(){
		execute("update organizations set name = 'Capital Health Medical Center-Hopewell' where nci_institute_code = 'NJ040'")
		execute("update organizations set name = 'Rutgers Cancer Institute of New Jersey-Robert Wood Johnson University Hospital' where nci_institute_code = 'NJ053'")
		execute("update organizations set name = 'Saint Luke\\'s Hospital-Warren Campus' where nci_institute_code = 'NJ062'")
		execute("update organizations set name = 'Jersey Shore University Medical Center' where nci_institute_code = 'NJ064'")
		execute("update organizations set name = 'Rutgers Cancer Institute of New Jersey' where nci_institute_code = 'NJ066'")
		execute("update organizations set name = 'Riverview Medical Center/Booker Cancer Center' where nci_institute_code = 'NJ067'")
		execute("update organizations set name = 'The Cancer Institute of New Jersey Hamilton' where nci_institute_code = 'NJ097'")
		execute("update organizations set name = 'Garden State Urology LLC' where nci_institute_code = 'NJ148'")
		execute("update organizations set name = 'GFH Surgical Associates' where nci_institute_code = 'NJ155'")
		execute("update organizations set name = 'Morristown Surgical Associates' where nci_institute_code = 'NJ168'")
		execute("update organizations set name = 'Kennedy Health Systems-Cancer Center' where nci_institute_code = 'NJ189'")
		execute("update organizations set name = 'Sparta Cancer Center' where nci_institute_code = 'NJ202'")
		execute("update organizations set name = 'Regional Cancer Care Associates LLC-Mount Holly' where nci_institute_code = 'NJ222'")
		execute("update organizations set name = 'AtlantiCare Cancer Care Institute' where nci_institute_code = 'NJ237'")
		execute("update organizations set name = 'Christus Saint Vincent Regional Medical Center' where nci_institute_code = 'NM007'")
		execute("update organizations set name = 'Memorial Medical Center-Main Campus' where nci_institute_code = 'NM013'")
		execute("update organizations set name = 'Kymera Cancer Center' where nci_institute_code = 'NM018'")
		execute("update organizations set name = 'Christus Saint Vincent Regional Cancer Center' where nci_institute_code = 'NM022'")
		execute("update organizations set name = 'Radiation Oncology Associates of Albuquerque' where nci_institute_code = 'NM033'")
		execute("update organizations set name = 'Memorial Medical Center-Las Cruces' where nci_institute_code = 'NM039'")
		execute("update organizations set name = 'HealthCare Partners Medical Group Oncology/Hematology-Maryland Parkway' where nci_institute_code = 'NV019'")
		execute("update organizations set name = 'Nevada Cancer Institute-Summerlin Campus' where nci_institute_code = 'NV039'")
		execute("update organizations set name = '21st Century Oncology-Vegas' where nci_institute_code = 'NV044'")
		execute("update organizations set name = 'Women\\'s Cancer Center of Nevada' where nci_institute_code = 'NV049'")
		execute("update organizations set name = 'Radiation Oncology Centers of Nevada Central' where nci_institute_code = 'NV053'")
	}
	
	void m21(){
		execute("update organizations set name = 'Comprehensive Cancer Centers of Nevada - Northwest' where nci_institute_code = 'NV054'")
		execute("update organizations set name = 'HealthCare Partners Medical Group Oncology/Hematology-Tenaya' where nci_institute_code = 'NV061'")
		execute("update organizations set name = 'Veterans Affairs New York Harbor Healthcare System' where nci_institute_code = 'NY007'")
		execute("update organizations set name = 'Montefiore Medical Center - Moses Campus' where nci_institute_code = 'NY045'")
		execute("update organizations set name = 'Unity Park Ridge Campus' where nci_institute_code = 'NY046'")
		execute("update organizations set name = 'Northern Westchester Hospital' where nci_institute_code = 'NY047'")
		execute("update organizations set name = 'University Hospital of Brooklyn at Long Island College Hospital' where nci_institute_code = 'NY067'")
		execute("update organizations set name = 'Aurelia Osborn Fox Memorial Hospital' where nci_institute_code = 'NY146'")
		execute("update organizations set name = 'UHS Wilson Medical Center' where nci_institute_code = 'NY148'")
		execute("update organizations set name = 'Women and Childrens Hospital of Buffalo' where nci_institute_code = 'NY157'")
		execute("update organizations set name = 'Hematology Oncology Associates of Central New York PC' where nci_institute_code = 'NY175'")
		execute("update organizations set name = 'Westchester Medical Center' where nci_institute_code = 'NY176'")
		execute("update organizations set name = 'Montefiore Medical Center-Wakefield Campus' where nci_institute_code = 'NY179'")
		execute("update organizations set name = 'North Shore-LIJ Health System CCOP' where nci_institute_code = 'NY188'")
		execute("update organizations set name = 'The Steven and Alexandra Cohen Children\\'s Medical Center of New York' where nci_institute_code = 'NY226'")
		execute("update organizations set name = 'Interlakes Foundation Inc-Rochester' where nci_institute_code = 'NY234'")
		execute("update organizations set name = 'Unity Saint Mary\\'s Campus' where nci_institute_code = 'NY291'")
		execute("update organizations set name = 'Montefiore Medical Center-Einstein Campus' where nci_institute_code = 'NY313'")
		execute("update organizations set name = 'Maimonides Cancer Center-Breast Cancer Program' where nci_institute_code = 'NY337'")
		execute("update organizations set name = 'New York Oncology Hematology PC -Albany Medical Center' where nci_institute_code = 'NY342'")
		execute("update organizations set name = 'Hematology Oncology Associates of Western Suffolk PC' where nci_institute_code = 'NY350'")
		execute("update organizations set name = 'Memorial Sloan-Kettering Cancer Center Rockville Centre' where nci_institute_code = 'NY353'")
		execute("update organizations set name = '21st Century Oncology-Yonkers' where nci_institute_code = 'NY356'")
		execute("update organizations set name = 'Beth Israel Comprehensive Cancer Center-West Side Campus' where nci_institute_code = 'NY358'")
		execute("update organizations set name = 'Island Gynecologic Oncology' where nci_institute_code = 'NY363'")
	}
	
	void m22(){
		execute("update organizations set name = 'The Dyson Center for Cancer Care' where nci_institute_code = 'NY386'")
		execute("update organizations set name = 'Women\\'s Cancer Care Associates LLC' where nci_institute_code = 'NY407'")
		execute("update organizations set name = 'Flower Hospital' where nci_institute_code = 'OH012'")
		execute("update organizations set name = 'Toledo Clinic Cancer Centers-Toledo' where nci_institute_code = 'OH016'")
		execute("update organizations set name = 'Cleveland Clinic Cancer Center/Fairview Hospital' where nci_institute_code = 'OH038'")
		execute("update organizations set name = 'Summa Barberton Hospital' where nci_institute_code = 'OH049'")
		execute("update organizations set name = 'Summa Akron City Hospital/Cooper Cancer Center' where nci_institute_code = 'OH055'")
		execute("update organizations set name = 'Springfield Regional Medical Center' where nci_institute_code = 'OH090'")
		execute("update organizations set name = 'The Toledo Hospital/Toledo Children\\'s Hospital' where nci_institute_code = 'OH099'")
		execute("update organizations set name = 'University Hospital/UC Barrett Cancer Center' where nci_institute_code = 'OH111'")
		execute("update organizations set name = 'Cancer Care Center Incorporated' where nci_institute_code = 'OH193'")
		execute("update organizations set name = 'Surgical Oncology Associates of Ohio' where nci_institute_code = 'OH261'")
		execute("update organizations set name = 'Lima Memorial Cancer Institute' where nci_institute_code = 'OH266'")
		execute("update organizations set name = 'Toledo Clinic Cancer Centers-Maumee' where nci_institute_code = 'OH282'")
		execute("update organizations set name = 'TriHealth Cancer Institute-Westside' where nci_institute_code = 'OH290'")
		execute("update organizations set name = 'Toledo Clinic Cancer Centers-Bowling Green' where nci_institute_code = 'OH295'")
		execute("update organizations set name = 'Cleveland Clinic Cancer Center Independence' where nci_institute_code = 'OH306'")
		execute("update organizations set name = 'Toledo Clinic Cancer Centers-Oregon' where nci_institute_code = 'OH309'")
		execute("update organizations set name = 'Genesis HealthCare System-Good Samaritan' where nci_institute_code = 'OH327'")
		execute("update organizations set name = 'Cleveland Clinic Cancer Center Beachwood' where nci_institute_code = 'OH359'")
		execute("update organizations set name = 'Ohio State University/Stoneridge Medical Center' where nci_institute_code = 'OH378'")
		execute("update organizations set name = 'Central Ohio Surgical Specialists Inc-Hilliard' where nci_institute_code = 'OH380'")
		execute("update organizations set name = 'Cancer Centers of Southwest Oklahoma Research' where nci_institute_code = 'OK027'")
		execute("update organizations set name = 'Tulsa Cancer Institute' where nci_institute_code = 'OK037'")
		execute("update organizations set name = 'Cancer Treatment Centers of America' where nci_institute_code = 'OK038'")
	}
	
	void m23(){
		execute("update organizations set name = 'Tulsa Cancer Institute-Stillwater' where nci_institute_code = 'OK045'")
		execute("update organizations set name = 'Mercy Clinic Oklahoma Communities Inc-Norman' where nci_institute_code = 'OK047'")
		execute("update organizations set name = 'Tulsa Cancer Institute-Bartlesville' where nci_institute_code = 'OK048'")
		execute("update organizations set name = 'Mercy Physicians of Oklahoma- Enid' where nci_institute_code = 'OK050'")
		execute("update organizations set name = 'Tulsa Cancer Institute-McAlester' where nci_institute_code = 'OK051'")
		execute("update organizations set name = 'Mercy Clinic Oklahoma Communities Inc-Mercy Health Center' where nci_institute_code = 'OK053'")
		execute("update organizations set name = 'Mercy Physicians of Oklahoma-Lakeside' where nci_institute_code = 'OK054'")
		execute("update organizations set name = 'Saint Anthony/Frank C Love Cancer Institute' where nci_institute_code = 'OK061'")
		execute("update organizations set name = 'Providence Willamette Falls Medical Center' where nci_institute_code = 'OR001'")
		execute("update organizations set name = 'Asante Rogue Regional Medical Center' where nci_institute_code = 'OR029'")
		execute("update organizations set name = 'Saint Charles Health System' where nci_institute_code = 'OR031'")
		execute("update organizations set name = 'Western Oncology Research Consortium' where nci_institute_code = 'OR037'")
		execute("update organizations set name = 'Mid-Columbia Medical Center/Celilo Cancer Center' where nci_institute_code = 'OR060'")
		execute("update organizations set name = 'Asante Three Rivers Medical Center' where nci_institute_code = 'OR066'")
		execute("update organizations set name = 'The Oregon Clinic Westside Surgical Specialists' where nci_institute_code = 'OR091'")
		execute("update organizations set name = 'OHSU Knight Cancer Institute-Northwest Portland' where nci_institute_code = 'OR096'")
		execute("update organizations set name = 'OHSU Knight Cancer Institute-Beaverton' where nci_institute_code = 'OR105'")
		execute("update organizations set name = 'OHSU Knight Cancer Institute-Mount Hood' where nci_institute_code = 'OR110'")
		execute("update organizations set name = 'Providence Oncology and Hematology Care Westside' where nci_institute_code = 'OR112'")
		execute("update organizations set name = 'Randall Children\\'s Hospital at Legacy Emanuel' where nci_institute_code = 'OR117'")
		execute("update organizations set name = 'UPMC-Heritage Valley Health System Beaver' where nci_institute_code = 'PA001'")
		execute("update organizations set name = 'Allegheny Valley Hospital' where nci_institute_code = 'PA002'")
		execute("update organizations set name = 'Allegheny General Hospital' where nci_institute_code = 'PA009'")
		execute("update organizations set name = 'Children\\'s Hospital of Pittsburgh of UPMC' where nci_institute_code = 'PA010'")
		execute("update organizations set name = 'UPMC-Magee Womens Hospital' where nci_institute_code = 'PA011'")
	}
	
	void m24(){	
		execute("update organizations set name = 'UPMC-Montefiore Hospital' where nci_institute_code = 'PA013'")
		execute("update organizations set name = 'UPMC-Presbyterian Hospital' where nci_institute_code = 'PA014'")
		execute("update organizations set name = 'University of Pittsburgh Cancer Institute (UPCI)' where nci_institute_code = 'PA015'")
		execute("update organizations set name = 'UPMC-Mercy Hospital' where nci_institute_code = 'PA017'")
		execute("update organizations set name = 'UPMC-Shadyside Hospital' where nci_institute_code = 'PA020'")
		execute("update organizations set name = 'UPMC Cancer Center-Washington' where nci_institute_code = 'PA040'")
		execute("update organizations set name = 'PinnacleHealth Fox Chase Regional Cancer Center-Community Campus' where nci_institute_code = 'PA045'")
		execute("update organizations set name = 'WellSpan Health-York Hospital' where nci_institute_code = 'PA047'")
		execute("update organizations set name = 'Saint Luke\\'s University Hospital-Bethlehem Campus' where nci_institute_code = 'PA054'")
		execute("update organizations set name = 'Regional Hospital of Scranton' where nci_institute_code = 'PA057'")
		execute("update organizations set name = 'Guthrie Clinic-Robert Packer Hospital' where nci_institute_code = 'PA062'")
		execute("update organizations set name = 'Mercy Philadelphia Hospital' where nci_institute_code = 'PA095'")
		execute("update organizations set name = 'Reading Hospital' where nci_institute_code = 'PA107'")
		execute("update organizations set name = 'Mercy Suburban Cancer Center' where nci_institute_code = 'PA111'")
		execute("update organizations set name = 'Aria Health-Torresdale Campus' where nci_institute_code = 'PA116'")
		execute("update organizations set name = 'Community General Hospital' where nci_institute_code = 'PA135'")
		execute("update organizations set name = 'UPMC Cancer Center at UPMC Northwest' where nci_institute_code = 'PA137'")
		execute("update organizations set name = 'Geisinger Wyoming Valley/Henry Cancer Center' where nci_institute_code = 'PA138'")
		execute("update organizations set name = 'WellSpan Health-Gettysburg Hospital' where nci_institute_code = 'PA157'")
		execute("update organizations set name = 'Butler Regional Cancer Center-Benbrook Commons' where nci_institute_code = 'PA166'")
		execute("update organizations set name = 'Cancer Care Associates-Medical Oncology' where nci_institute_code = 'PA175'")
		execute("update organizations set name = 'UPMC-Passavant Hospital' where nci_institute_code = 'PA197'")
		execute("update organizations set name = 'Geisinger Medical Center-Cancer Center Hazelton' where nci_institute_code = 'PA209'")
		execute("update organizations set name = 'Saint Luke\\'s Hospital-Quakertown Campus' where nci_institute_code = 'PA211'")
		execute("update organizations set name = 'Hahnemann University Hospital' where nci_institute_code = 'PA215'")
	}
	
	void m25(){
		execute("update organizations set name = 'WellSpan Health-York Cancer Center' where nci_institute_code = 'PA254'")
		execute("update organizations set name = 'UPMC Cancer Center-Uniontown' where nci_institute_code = 'PA256'")
		execute("update organizations set name = 'The Regional Cancer Center-Medical Oncology Hematology' where nci_institute_code = 'PA264'")
		execute("update organizations set name = 'Saint Luke\\'s Hospital-Miners Campus' where nci_institute_code = 'PA267'")
		execute("update organizations set name = 'UPMC-Johnstown/John P. Murtha Regional Cancer Center' where nci_institute_code = 'PA270'")
		execute("update organizations set name = 'UPMC Cancer Center-Indiana' where nci_institute_code = 'PA313'")
		execute("update organizations set name = 'UPMC-Heritage Valley Health Sewickley' where nci_institute_code = 'PA322'")
		execute("update organizations set name = 'UPMC Cancer Center-Natrona Heights' where nci_institute_code = 'PA326'")
		execute("update organizations set name = 'Penn State Hershey Children\\'s Hospital' where nci_institute_code = 'PA335'")
		execute("update organizations set name = 'UPMC-Saint Clair Hospital Cancer Center' where nci_institute_code = 'PA351'")
		execute("update organizations set name = 'UPMC-Coraopolis/Heritage Valley Radiation Oncology' where nci_institute_code = 'PA353'")
		execute("update organizations set name = 'Alliance Cancer Specialists PC-Sellersville' where nci_institute_code = 'PA358'")
		execute("update organizations set name = 'Hematology Oncology Medical Specialists' where nci_institute_code = 'PA366'")
		execute("update organizations set name = 'UPMC-Uniontown/Robert E. Eberly Pavilion' where nci_institute_code = 'PA371'")
		execute("update organizations set name = 'The Regional Cancer Center-Radiation Oncology' where nci_institute_code = 'PA378'")
		execute("update organizations set name = 'Alliance Cancer Specialists PC-Chalfont' where nci_institute_code = 'PA383'")
		execute("update organizations set name = 'Gettysburg Surgical Associates' where nci_institute_code = 'PA396'")
		execute("update organizations set name = 'UPMC Cancer Center at UPMC Horizon' where nci_institute_code = 'PA406'")
		execute("update organizations set name = 'Comprehensive Breast Care Institute at DSI of Bucks County' where nci_institute_code = 'PA420'")
		execute("update organizations set name = 'Yolanda G Barco Oncology Institute' where nci_institute_code = 'PA423'")
		execute("update organizations set name = 'Alliance Cancer Specialists PC-Doylestown' where nci_institute_code = 'PA428'")
		execute("update organizations set name = 'Maryland Hematology Oncology - Gettysburg' where nci_institute_code = 'PA431'")
		execute("update organizations set name = 'Roger Williams Medical Center' where nci_institute_code = 'RI007'")
		execute("update organizations set name = 'Women and Infants Hospital' where nci_institute_code = 'RI012'")
		execute("update organizations set name = 'Self Regional Healthcare' where nci_institute_code = 'SC015'")
	}
	
	void m26(){
		execute("update organizations set name = 'Associated Medical Specialists PA dba Coastal Cancer Center' where nci_institute_code = 'SC023'")
		execute("update organizations set name = 'Greenville Health System Cancer Instutite/Greenville CCOP' where nci_institute_code = 'SC036'")
		execute("update organizations set name = 'Greenville Health System Cancer Institute-Andrews' where nci_institute_code = 'SC038'")
		execute("update organizations set name = 'Greenville Health System Cancer Institute-Butternut' where nci_institute_code = 'SC053'")
		execute("update organizations set name = 'Greenville Health System Cancer Institute-Seneca' where nci_institute_code = 'SC054'")
		execute("update organizations set name = 'Greenville Health System Cancer Institute-Easley' where nci_institute_code = 'SC055'")
		execute("update organizations set name = 'Greenville Health System Cancer Institute-Spartanburg' where nci_institute_code = 'SC056'")
		execute("update organizations set name = 'Greenville Health System Cancer Institute-Faris' where nci_institute_code = 'SC060'")
		execute("update organizations set name = 'Sanford USD Medical Center - Sioux Falls' where nci_institute_code = 'SD003'")
		execute("update organizations set name = 'Sanford Cancer Center Oncology Clinic' where nci_institute_code = 'SD004'")
		execute("update organizations set name = 'Sanford Research USD' where nci_institute_code = 'SD011'")
		execute("update organizations set name = 'Avera Saint Luke\\'s Hospital and Cancer Center' where nci_institute_code = 'SD027'")
		execute("update organizations set name = 'Vanderbilt University/Ingram Cancer Center' where nci_institute_code = 'TN008'")
		execute("update organizations set name = 'Johnson City Medical Center-Mountain States Health Alliance' where nci_institute_code = 'TN011'")
		execute("update organizations set name = 'East Tennessee Baptist Hospital-Mercy Health Partners' where nci_institute_code = 'TN019'")
		execute("update organizations set name = 'Baptist Memorial Hospital and Cancer Center-Memphis' where nci_institute_code = 'TN029'")
		execute("update organizations set name = 'Vanderbilt-Ingram Cancer Center Cool Springs' where nci_institute_code = 'TN092'")
		execute("update organizations set name = 'Integrity Oncology PLLC-Collierville' where nci_institute_code = 'TN098'")
		execute("update organizations set name = 'Tennessee Oncology PLLC-Chattanooga' where nci_institute_code = 'TN100'")
		execute("update organizations set name = 'Women’s Institute for Specialized Health' where nci_institute_code = 'TN114'")
		execute("update organizations set name = 'Wellmont Medical Associates-Oncology and Hematology' where nci_institute_code = 'TN122'")
		execute("update organizations set name = 'The Surgical Clinic PLLC-Saint Thomas' where nci_institute_code = 'TN123'")
		execute("update organizations set name = 'Tennessee Oncology PLLC-Saint Thomas' where nci_institute_code = 'TN133'")
		execute("update organizations set name = 'Knoxville Gynecologic Cancer Specialists PC' where nci_institute_code = 'TN153'")
		execute("update organizations set name = 'Texas Health Presbyterian Hospital Dallas' where nci_institute_code = 'TX005'")
	}
	
	void m27(){	
		execute("update organizations set name = 'Texas Health Harris Methodist Hospital Fort Worth' where nci_institute_code = 'TX008'")
		execute("update organizations set name = 'The Methodist Hospital System' where nci_institute_code = 'TX036'")
		execute("update organizations set name = 'US Oncology Research LLC' where nci_institute_code = 'TX053'")
		execute("update organizations set name = 'Midland Memorial Hospital-Main Campus' where nci_institute_code = 'TX058'")
		execute("update organizations set name = 'Texas Oncology-Memorial City' where nci_institute_code = 'TX082'")
		execute("update organizations set name = 'Baylor All Saints Medical Center at Fort Worth' where nci_institute_code = 'TX102'")
		execute("update organizations set name = 'Texas Oncology-Longview Cancer Center' where nci_institute_code = 'TX108'")
		execute("update organizations set name = 'Texas Oncology-Bedford Edwards Cancer Center' where nci_institute_code = 'TX115'")
		execute("update organizations set name = 'Cancer Care Centers of South Texas' where nci_institute_code = 'TX118'")
		execute("update organizations set name = 'Texas Oncology at Baylor Irving Cancer Center' where nci_institute_code = 'TX132'")
		execute("update organizations set name = 'Texas Oncology-Austin Midtown' where nci_institute_code = 'TX137'")
		execute("update organizations set name = 'South Texas Pediatrics-MBCCOP' where nci_institute_code = 'TX140'")
		execute("update organizations set name = 'Smith Clinic-Houston' where nci_institute_code = 'TX143'")
		execute("update organizations set name = 'Texas Oncology-Midland Allison Cancer Center' where nci_institute_code = 'TX157'")
		execute("update organizations set name = 'Texas Oncology-Houston Medical Center' where nci_institute_code = 'TX159'")
		execute("update organizations set name = 'Baylor Medical Center at Garland' where nci_institute_code = 'TX183'")
		execute("update organizations set name = 'Texas Oncology-McAllen' where nci_institute_code = 'TX232'")
		execute("update organizations set name = 'Texas Oncology-Wichita Falls Texoma Cancer Center' where nci_institute_code = 'TX241'")
		execute("update organizations set name = 'Institute of Oncology and Hematology Biomedical Research' where nci_institute_code = 'TX261'")
		execute("update organizations set name = 'Texas Oncology-Waco Highway 6' where nci_institute_code = 'TX264'")
		execute("update organizations set name = 'Texas Oncology at Baylor Charles A Sammons Cancer Center' where nci_institute_code = 'TX267'")
		execute("update organizations set name = 'Scott and White Healthcare Round Rock' where nci_institute_code = 'TX331'")
		execute("update organizations set name = 'Huntsman Cancer Institute/University of Utah' where nci_institute_code = 'UT003'")
		execute("update organizations set name = 'Dixie Regional Medical Center-River Road Campus' where nci_institute_code = 'UT038'")
		execute("update organizations set name = 'Huntsman Intermountain Cancer Center-American Fork Hospital' where nci_institute_code = 'UT053'")
	}
	
	void m28(){
		execute("update organizations set name = 'Virginia Oncology Associates-Newport News' where nci_institute_code = 'VA039'")
		execute("update organizations set name = 'Medical Specialists Of Fredericksburg' where nci_institute_code = 'VA045'")
		execute("update organizations set name = 'Rockingham Memorial Hospital Hahn Cancer Center' where nci_institute_code = 'VA063'")
		execute("update organizations set name = 'Virginia Cancer Specialists PC-Alexandria' where nci_institute_code = 'VA065'")
		execute("update organizations set name = 'Shenandoah Oncology PC' where nci_institute_code = 'VA066'")
		execute("update organizations set name = 'Prince William Hospital' where nci_institute_code = 'VA073'")
		execute("update organizations set name = 'Virginia Oncology Associates-Hampton' where nci_institute_code = 'VA084'")
		execute("update organizations set name = 'Virginia Cancer Specialists-Alexandria' where nci_institute_code = 'VA109'")
		execute("update organizations set name = 'Virginia Cancer Specialists-Fairfax' where nci_institute_code = 'VA111'")
		execute("update organizations set name = 'Augusta Health/Hematology Oncology Patient Enterprise (HOPE)' where nci_institute_code = 'VA118'")
		execute("update organizations set name = 'Virginia Cancer Specialists PC-Woodbridge' where nci_institute_code = 'VA120'")
		execute("update organizations set name = 'Urology of Virginia PLLC' where nci_institute_code = 'VA128'")
		execute("update organizations set name = 'Carilion Clinic Gynecological Oncology' where nci_institute_code = 'VA131'")
		execute("update organizations set name = 'Virginia Cancer Specialists-Gainesville' where nci_institute_code = 'VA133'")
		execute("update organizations set name = 'Peninsula Cancer Institute-Newport News' where nci_institute_code = 'VA136'")
		execute("update organizations set name = 'Peninsula Cancer institute-Williamsburg' where nci_institute_code = 'VA137'")
		execute("update organizations set name = 'Virginia Cancer Specialists PC-Arlington' where nci_institute_code = 'VA138'")
		execute("update organizations set name = 'Virginia Cancer Specialists-Fair Oaks' where nci_institute_code = 'VA139'")
		execute("update organizations set name = 'George Mason University-Fairfax Campus' where nci_institute_code = 'VA141'")
		execute("update organizations set name = 'Peninsula Cancer Institute-Gloucester' where nci_institute_code = 'VA143'")
		execute("update organizations set name = 'Sentara Surgery Specialists-Jefferson' where nci_institute_code = 'VA149'")
		execute("update organizations set name = 'Virginia Oncology Associates-Princess Anne' where nci_institute_code = 'VA155'")
		execute("update organizations set name = 'Fletcher Allen Health Care-Medical Center' where nci_institute_code = 'VT003'")
		execute("update organizations set name = 'Central Vermont Medical Center/National Life Cancer Treatment' where nci_institute_code = 'VT019'")
		execute("update organizations set name = 'Southwestern Vermont Healthcare Oncology Associates' where nci_institute_code = 'VT023'")
	}
	
	void m29(){
		execute("update organizations set name = 'Swedish Medical Center-Edmonds' where nci_institute_code = 'WA002'")
		execute("update organizations set name = 'Swedish Medical Center-Ballard Campus' where nci_institute_code = 'WA009'")
		execute("update organizations set name = 'PeaceHealth Southwest Medical Center' where nci_institute_code = 'WA037'")
		execute("update organizations set name = 'Providence Holy Family Hospital' where nci_institute_code = 'WA048'")
		execute("update organizations set name = 'Providence Sacred Heart Medical Center and Children\\'s Hospital' where nci_institute_code = 'WA050'")
		execute("update organizations set name = 'Providence Saint Mary Regional Cancer Center' where nci_institute_code = 'WA053'")
		execute("update organizations set name = 'Seattle Children\\'s Hospital' where nci_institute_code = 'WA061'")
		execute("update organizations set name = 'Tacoma/Valley Radiation Oncology Centers-Jackson Hall' where nci_institute_code = 'WA067'")
		execute("update organizations set name = 'PeaceHealth Saint Joseph Medical Center' where nci_institute_code = 'WA069'")
		execute("update organizations set name = 'Seattle Cancer Care Alliance at EvergreenHealth' where nci_institute_code = 'WA100'")
		execute("update organizations set name = 'Harrison Bremerton Hematology and Oncology' where nci_institute_code = 'WA113'")
		execute("update organizations set name = 'PeaceHealth Southwest Cancer Center' where nci_institute_code = 'WA140'")
		execute("update organizations set name = 'Gundersen Lutheran Health System/CCOP' where nci_institute_code = 'WI029'")
		execute("update organizations set name = 'Mayo Clinic Health System Eau Claire Hospital-Luther Campus' where nci_institute_code = 'WI036'")
		execute("update organizations set name = 'Aurora Cancer Care-Milwaukee South' where nci_institute_code = 'WI044'")
		execute("update organizations set name = 'Mayo Clinic Health System-Eau Claire Clinic' where nci_institute_code = 'WI045'")
		execute("update organizations set name = 'Dean Hematology and Oncology Clinic' where nci_institute_code = 'WI059'")
		execute("update organizations set name = 'Mayo Clinic Health System-Franciscan Healthcare' where nci_institute_code = 'WI077'")
		execute("update organizations set name = 'Saint Agnes Hospital/Agnesian Cancer Center' where nci_institute_code = 'WI098'")
		execute("update organizations set name = 'Aurora Cancer Care-Glendale' where nci_institute_code = 'WI099'")
		execute("update organizations set name = 'Aurora Cancer Care-Franklin' where nci_institute_code = 'WI104'")
		execute("update organizations set name = 'Aurora Cancer Care-Southern Lakes' where nci_institute_code = 'WI114'")
		execute("update organizations set name = 'Aurora Cancer Care-Kenosha South' where nci_institute_code = 'WI121'")
		execute("update organizations set name = 'Marshfield Clinic Cancer Center at Sacred Heart' where nci_institute_code = 'WI134'")
		execute("update organizations set name = 'Aurora Cancer Care-Milwaukee West' where nci_institute_code = 'WI135'")
	}
	
	void m30(){
		execute("update organizations set name = 'Wheaton Franciscan Healthcare-Saint Francis Inc' where nci_institute_code = 'WI137'")
		execute("update organizations set name = 'Comprehensive Breast Health Center' where nci_institute_code = 'WI150'")
		execute("update organizations set name = 'Kraemer Cancer Center' where nci_institute_code = 'WI160'")
		execute("update organizations set name = 'WVUH-East City Hospital' where nci_institute_code = 'WV006'")
		execute("update organizations set name = 'Wheeling Hospital/Schiffler Cancer Center' where nci_institute_code = 'WV013'")
		execute("update organizations set name = 'West Virginia University Healthcare' where nci_institute_code = 'WV025'")
		execute("update organizations set name = 'National Institute of Allergy and Infectious Diseases' where nci_institute_code = 'NIAID'")
		execute("update organizations set name = 'National Institute of Arthritis and Musculoskeletal and Skin Diseases' where nci_institute_code = 'NIAMS'")
	}
	
 void down() {
  }
}