package gov.nih.nci.ctcae.core.helper;

import gov.nih.nci.ctcae.core.domain.*;
import gov.nih.nci.ctcae.core.repository.*;
import gov.nih.nci.ctcae.core.query.ProCtcTermQuery;
import gov.nih.nci.ctcae.core.query.CRFQuery;

import java.util.List;
import java.util.Date;
import java.text.ParseException;

/**
 * User: Harsh
 * Date: Jun 5, 2009
 * Time: 8:40:02 AM
 */
public class CrfTestHelper {

    private static final int numberOfSymptoms = 10;
    private static List<ProCtcTerm> proCtcTerms;
    private static final String formTitle = "Auto-Generated Form";
    private static CRFRepository crfRepository;
    private static ProCtcTermRepository proCtcTermRepository;

    private CrfTestHelper() {

    }

    public static void inititalize() {
        crfRepository = TestDataManager.crfRepository;
        proCtcTermRepository = TestDataManager.proCtcTermRepository;
    }

    public static void createTestForm() throws ParseException {
        deleteAutoGeneratedForms();
        CRF crf = new CRF();
        firstTab_SelectStudy(crf);
        secondTab_FormBuilder(crf);
        thirdTab_ScheduleTemplate(crf);
        fourthTab_Notifications(crf);
        crfRepository.save(crf);
        ParticipantTestHelper.createParticipant("Charlie","Boon","1-4",crf.getStudy().getLeadStudySite());
        crf.setEffectiveStartDate(new Date());
        crfRepository.updateStatusToReleased(crf);
    }

    private static void firstTab_SelectStudy(CRF crf) {
        crf.setStudy(StudyTestHelper.getDefaultStudy());
    }

    private static void secondTab_FormBuilder(CRF crf) {
        ProCtcTermQuery query = new ProCtcTermQuery();
        query.filterByCtcTermHavingQuestionsOnly();
        proCtcTerms = (List<ProCtcTerm>) proCtcTermRepository.find(query);
        crf.setTitle(formTitle);
        crf.setCrfVersion("1.0");
        for (int i = 0; i < numberOfSymptoms; i++) {
            crf.addProCtcTerm(proCtcTerms.get(i));
        }
    }

    private static void thirdTab_ScheduleTemplate(CRF crf) {

        CRFCalendar calendar = new CRFCalendar();
        calendar.setRepeatEveryAmount("2");
        calendar.setRepeatEveryUnit("Days");
        calendar.setDueDateAmount("24");
        calendar.setDueDateUnit("Hours");
        calendar.setRepeatUntilAmount("2");
        calendar.setRepeatUntilUnit("Number");

        crf.addCrfCalendar(calendar);
        
        CRFCycleDefinition defA = new CRFCycleDefinition();
        defA.setCycleLength(14);
        defA.setCycleLengthUnit("Days");
        defA.setRepeatTimes("2");
        defA.setOrder(0);

        CRFCycle cycle1 = new CRFCycle();
        cycle1.setOrder(0);
        cycle1.setCycleDays(",1,8,13");
        defA.addCrfCycle(cycle1);

        CRFCycle cycle2 = new CRFCycle();
        cycle2.setOrder(1);
        cycle2.setCycleDays(",3,8,11");
        defA.addCrfCycle(cycle2);

        crf.addCrfCycleDefinition(defA);

        CRFCycleDefinition defB = new CRFCycleDefinition();
        defB.setCycleLength(21);
        defB.setCycleLengthUnit("Days");
        defB.setRepeatTimes("2");
        defB.setOrder(1);

        CRFCycle cycle3 = new CRFCycle();
        cycle3.setOrder(0);
        cycle3.setCycleDays(",4,10,18,21");
        defB.addCrfCycle(cycle3);

        CRFCycle cycle4 = new CRFCycle();
        cycle4.setOrder(1);
        cycle4.setCycleDays(",5,11,19");
        defB.addCrfCycle(cycle4);

        crf.addCrfCycleDefinition(defB);
    }

    private static void fourthTab_Notifications(CRF crf) {

    }

    private static void deleteAutoGeneratedForms() {
        CRFQuery query = new CRFQuery();
        query.filterByTitleExactMatch(formTitle);
        List<CRF> crfs = (List<CRF>) crfRepository.find(query);
        for (CRF crf : crfs) {
            crfRepository.delete(crf);
        }
    }

}